#ifndef X86_MSR_ADDERESSES_H
#define X86_MSR_ADDERESSES_H

/*
 *  Free Public License 1.0.0
 *  Permission to use, copy, modify, and/or distribute this software for any
 *  purpose with or without fee is hereby granted.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 *  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF 
 *  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 *  ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES 
 *  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN 
 *  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF 
 *  OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

/*
 *  Naming Convention:
 *  Each constant is named by prefixing "MSR_" to the name in the Intel's
 *  manual. (e.g. IA32_TIME_STAMP_COUNTER -> MSR_IA32_TIME_STAMP_COUNTER)
 *  If the original Intel's name is prefixed with "MSR_", the corresponding
 *  constant has the exact same name.
 *
 *  CAUTION:
 *  This file is automatically generated from Intel 64 and IA-32
 *  Architectures Software Developer Manuals. This may contain garbage or
 *  incorrect definitions.
 */



/*
 * 35.1 ARCHITECTURAL MSRS
 */
#define MSR_IA32_P5_MC_ADDR                  0x00000000U
#define MSR_IA32_P5_MC_TYPE                  0x00000001U
#define MSR_IA32_MONITOR_FILTER_SIZE         0x00000006U
#define MSR_IA32_TIME_STAMP_COUNTER          0x00000010U
#define MSR_IA32_PLATFORM_ID                 0x00000017U
#define MSR_IA32_APIC_BASE                   0x0000001bU
#define MSR_IA32_FEATURE_CONTROL             0x0000003aU
#define MSR_IA32_TSC_ADJUST                  0x0000003bU
#define MSR_IA32_BIOS_UPDT_TRIG              0x00000079U
#define MSR_IA32_BIOS_SIGN_ID                0x0000008bU
#define MSR_IA32_SGXLEPUBKEYHASH0            0x0000008cU
#define MSR_IA32_SGXLEPUBKEYHASH1            0x0000008dU
#define MSR_IA32_SGXLEPUBKEYHASH2            0x0000008eU
#define MSR_IA32_SGXLEPUBKEYHASH3            0x0000008fU
#define MSR_IA32_SMM_MONITOR_CTL             0x0000009bU
#define MSR_IA32_SMBASE                      0x0000009eU
#define MSR_IA32_PMC0                        0x000000c1U
#define MSR_IA32_PMC1                        0x000000c2U
#define MSR_IA32_PMC2                        0x000000c3U
#define MSR_IA32_PMC3                        0x000000c4U
#define MSR_IA32_PMC4                        0x000000c5U
#define MSR_IA32_PMC5                        0x000000c6U
#define MSR_IA32_PMC6                        0x000000c7U
#define MSR_IA32_PMC7                        0x000000c8U
#define MSR_IA32_MPERF                       0x000000e7U
#define MSR_IA32_APERF                       0x000000e8U
#define MSR_IA32_MTRRCAP                     0x000000feU
#define MSR_IA32_SYSENTER_CS                 0x00000174U
#define MSR_IA32_SYSENTER_ESP                0x00000175U
#define MSR_IA32_SYSENTER_EIP                0x00000176U
#define MSR_IA32_MCG_CAP                     0x00000179U
#define MSR_IA32_MCG_STATUS                  0x0000017aU
#define MSR_IA32_MCG_CTL                     0x0000017bU
#define MSR_IA32_PERFEVTSEL0                 0x00000186U
#define MSR_IA32_PERFEVTSEL1                 0x00000187U
#define MSR_IA32_PERFEVTSEL2                 0x00000188U
#define MSR_IA32_PERFEVTSEL3                 0x00000189U
#define MSR_IA32_PERF_STATUS                 0x00000198U
#define MSR_IA32_PERF_CTL                    0x00000199U
#define MSR_IA32_CLOCK_MODULATION            0x0000019aU
#define MSR_IA32_THERM_INTERRUPT             0x0000019bU
#define MSR_IA32_THERM_STATUS                0x0000019cU
#define MSR_IA32_MISC_ENABLE                 0x000001a0U
#define MSR_IA32_ENERGY_PERF_BIAS            0x000001b0U
#define MSR_IA32_PACKAGE_THERM_STATUS        0x000001b1U
#define MSR_IA32_PACKAGE_THERM_INTERRUPT     0x000001b2U
#define MSR_IA32_DEBUGCTL                    0x000001d9U
#define MSR_IA32_SMRR_PHYSBASE               0x000001f2U
#define MSR_IA32_SMRR_PHYSMASK               0x000001f3U
#define MSR_IA32_PLATFORM_DCA_CAP            0x000001f8U
#define MSR_IA32_CPU_DCA_CAP                 0x000001f9U
#define MSR_IA32_DCA_0_CAP                   0x000001faU
#define MSR_IA32_MTRR_PHYSBASE0              0x00000200U
#define MSR_IA32_MTRR_PHYSMASK0              0x00000201U
#define MSR_IA32_MTRR_PHYSBASE1              0x00000202U
#define MSR_IA32_MTRR_PHYSMASK1              0x00000203U
#define MSR_IA32_MTRR_PHYSBASE2              0x00000204U
#define MSR_IA32_MTRR_PHYSMASK2              0x00000205U
#define MSR_IA32_MTRR_PHYSBASE3              0x00000206U
#define MSR_IA32_MTRR_PHYSMASK3              0x00000207U
#define MSR_IA32_MTRR_PHYSBASE4              0x00000208U
#define MSR_IA32_MTRR_PHYSMASK4              0x00000209U
#define MSR_IA32_MTRR_PHYSBASE5              0x0000020aU
#define MSR_IA32_MTRR_PHYSMASK5              0x0000020bU
#define MSR_IA32_MTRR_PHYSBASE6              0x0000020cU
#define MSR_IA32_MTRR_PHYSMASK6              0x0000020dU
#define MSR_IA32_MTRR_PHYSBASE7              0x0000020eU
#define MSR_IA32_MTRR_PHYSMASK7              0x0000020fU
#define MSR_IA32_MTRR_PHYSBASE8              0x00000210U
#define MSR_IA32_MTRR_PHYSMASK8              0x00000211U
#define MSR_IA32_MTRR_PHYSBASE9              0x00000212U
#define MSR_IA32_MTRR_PHYSMASK9              0x00000213U
#define MSR_IA32_MTRR_FIX64K_00000           0x00000250U
#define MSR_IA32_MTRR_FIX16K_80000           0x00000258U
#define MSR_IA32_MTRR_FIX16K_A0000           0x00000259U
#define MSR_IA32_MTRR_FIX4K_C0000            0x00000268U
#define MSR_IA32_MTRR_FIX4K_C8000            0x00000269U
#define MSR_IA32_MTRR_FIX4K_D0000            0x0000026aU
#define MSR_IA32_MTRR_FIX4K_D8000            0x0000026bU
#define MSR_IA32_MTRR_FIX4K_E0000            0x0000026cU
#define MSR_IA32_MTRR_FIX4K_E8000            0x0000026dU
#define MSR_IA32_MTRR_FIX4K_F0000            0x0000026eU
#define MSR_IA32_MTRR_FIX4K_F8000            0x0000026fU
#define MSR_IA32_PAT                         0x00000277U
#define MSR_IA32_MC0_CTL2                    0x00000280U
#define MSR_IA32_MC1_CTL2                    0x00000281U
#define MSR_IA32_MC2_CTL2                    0x00000282U
#define MSR_IA32_MC3_CTL2                    0x00000283U
#define MSR_IA32_MC4_CTL2                    0x00000284U
#define MSR_IA32_MC5_CTL2                    0x00000285U
#define MSR_IA32_MC6_CTL2                    0x00000286U
#define MSR_IA32_MC7_CTL2                    0x00000287U
#define MSR_IA32_MC8_CTL2                    0x00000288U
#define MSR_IA32_MC9_CTL2                    0x00000289U
#define MSR_IA32_MC10_CTL2                   0x0000028aU
#define MSR_IA32_MC11_CTL2                   0x0000028bU
#define MSR_IA32_MC12_CTL2                   0x0000028cU
#define MSR_IA32_MC13_CTL2                   0x0000028dU
#define MSR_IA32_MC14_CTL2                   0x0000028eU
#define MSR_IA32_MC15_CTL2                   0x0000028fU
#define MSR_IA32_MC16_CTL2                   0x00000290U
#define MSR_IA32_MC17_CTL2                   0x00000291U
#define MSR_IA32_MC18_CTL2                   0x00000292U
#define MSR_IA32_MC19_CTL2                   0x00000293U
#define MSR_IA32_MC20_CTL2                   0x00000294U
#define MSR_IA32_MC21_CTL2                   0x00000295U
#define MSR_IA32_MC22_CTL2                   0x00000296U
#define MSR_IA32_MC23_CTL2                   0x00000297U
#define MSR_IA32_MC24_CTL2                   0x00000298U
#define MSR_IA32_MC25_CTL2                   0x00000299U
#define MSR_IA32_MC26_CTL2                   0x0000029aU
#define MSR_IA32_MC27_CTL2                   0x0000029bU
#define MSR_IA32_MC28_CTL2                   0x0000029cU
#define MSR_IA32_MC29_CTL2                   0x0000029dU
#define MSR_IA32_MC30_CTL2                   0x0000029eU
#define MSR_IA32_MC31_CTL2                   0x0000029fU
#define MSR_IA32_MTRR_DEF_TYPE               0x000002ffU
#define MSR_IA32_FIXED_CTR0                  0x00000309U
#define MSR_IA32_FIXED_CTR1                  0x0000030aU
#define MSR_IA32_FIXED_CTR2                  0x0000030bU
#define MSR_IA32_PERF_CAPABILITIES           0x00000345U
#define MSR_IA32_FIXED_CTR_CTRL              0x0000038dU
#define MSR_IA32_PERF_GLOBAL_STATUS          0x0000038eU
#define MSR_IA32_PERF_GLOBAL_CTRL            0x0000038fU
#define MSR_IA32_PERF_GLOBAL_OVF_CTRL        0x00000390U
#define MSR_IA32_PERF_GLOBAL_STATUS_RESET    0x00000390U
#define MSR_IA32_PERF_GLOBAL_STATUS_SET      0x00000391U
#define MSR_IA32_PERF_GLOBAL_INUSE           0x00000392U
#define MSR_IA32_PEBS_ENABLE                 0x000003f1U
#define MSR_IA32_MC0_CTL                     0x00000400U
#define MSR_IA32_MC0_STATUS                  0x00000401U
#define MSR_IA32_MC0_ADDR                    0x00000402U
#define MSR_IA32_MC0_MISC                    0x00000403U
#define MSR_IA32_MC1_CTL                     0x00000404U
#define MSR_IA32_MC1_STATUS                  0x00000405U
#define MSR_IA32_MC1_ADDR                    0x00000406U
#define MSR_IA32_MC1_MISC                    0x00000407U
#define MSR_IA32_MC2_CTL                     0x00000408U
#define MSR_IA32_MC2_STATUS                  0x00000409U
#define MSR_IA32_MC2_ADDR                    0x0000040aU
#define MSR_IA32_MC2_MISC                    0x0000040bU
#define MSR_IA32_MC3_CTL                     0x0000040cU
#define MSR_IA32_MC3_STATUS                  0x0000040dU
#define MSR_IA32_MC3_ADDR                    0x0000040eU
#define MSR_IA32_MC3_MISC                    0x0000040fU
#define MSR_IA32_MC4_CTL                     0x00000410U
#define MSR_IA32_MC4_STATUS                  0x00000411U
#define MSR_IA32_MC4_ADDR                    0x00000412U
#define MSR_IA32_MC4_MISC                    0x00000413U
#define MSR_IA32_MC5_CTL                     0x00000414U
#define MSR_IA32_MC5_STATUS                  0x00000415U
#define MSR_IA32_MC5_ADDR                    0x00000416U
#define MSR_IA32_MC5_MISC                    0x00000417U
#define MSR_IA32_MC6_CTL                     0x00000418U
#define MSR_IA32_MC6_STATUS                  0x00000419U
#define MSR_IA32_MC6_ADDR                    0x0000041aU
#define MSR_IA32_MC6_MISC                    0x0000041bU
#define MSR_IA32_MC7_CTL                     0x0000041cU
#define MSR_IA32_MC7_STATUS                  0x0000041dU
#define MSR_IA32_MC7_ADDR                    0x0000041eU
#define MSR_IA32_MC7_MISC                    0x0000041fU
#define MSR_IA32_MC8_CTL                     0x00000420U
#define MSR_IA32_MC8_STATUS                  0x00000421U
#define MSR_IA32_MC8_ADDR                    0x00000422U
#define MSR_IA32_MC8_MISC                    0x00000423U
#define MSR_IA32_MC9_CTL                     0x00000424U
#define MSR_IA32_MC9_STATUS                  0x00000425U
#define MSR_IA32_MC9_ADDR                    0x00000426U
#define MSR_IA32_MC9_MISC                    0x00000427U
#define MSR_IA32_MC10_CTL                    0x00000428U
#define MSR_IA32_MC10_STATUS                 0x00000429U
#define MSR_IA32_MC10_ADDR                   0x0000042aU
#define MSR_IA32_MC10_MISC                   0x0000042bU
#define MSR_IA32_MC11_CTL                    0x0000042cU
#define MSR_IA32_MC11_STATUS                 0x0000042dU
#define MSR_IA32_MC11_ADDR                   0x0000042eU
#define MSR_IA32_MC11_MISC                   0x0000042fU
#define MSR_IA32_MC12_CTL                    0x00000430U
#define MSR_IA32_MC12_STATUS                 0x00000431U
#define MSR_IA32_MC12_ADDR                   0x00000432U
#define MSR_IA32_MC12_MISC                   0x00000433U
#define MSR_IA32_MC13_CTL                    0x00000434U
#define MSR_IA32_MC13_STATUS                 0x00000435U
#define MSR_IA32_MC13_ADDR                   0x00000436U
#define MSR_IA32_MC13_MISC                   0x00000437U
#define MSR_IA32_MC14_CTL                    0x00000438U
#define MSR_IA32_MC14_STATUS                 0x00000439U
#define MSR_IA32_MC14_ADDR                   0x0000043aU
#define MSR_IA32_MC14_MISC                   0x0000043bU
#define MSR_IA32_MC15_CTL                    0x0000043cU
#define MSR_IA32_MC15_STATUS                 0x0000043dU
#define MSR_IA32_MC15_ADDR                   0x0000043eU
#define MSR_IA32_MC15_MISC                   0x0000043fU
#define MSR_IA32_MC16_CTL                    0x00000440U
#define MSR_IA32_MC16_STATUS                 0x00000441U
#define MSR_IA32_MC16_ADDR                   0x00000442U
#define MSR_IA32_MC16_MISC                   0x00000443U
#define MSR_IA32_MC17_CTL                    0x00000444U
#define MSR_IA32_MC17_STATUS                 0x00000445U
#define MSR_IA32_MC17_ADDR                   0x00000446U
#define MSR_IA32_MC17_MISC                   0x00000447U
#define MSR_IA32_MC18_CTL                    0x00000448U
#define MSR_IA32_MC18_STATUS                 0x00000449U
#define MSR_IA32_MC18_ADDR                   0x0000044aU
#define MSR_IA32_MC18_MISC                   0x0000044bU
#define MSR_IA32_MC19_CTL                    0x0000044cU
#define MSR_IA32_MC19_STATUS                 0x0000044dU
#define MSR_IA32_MC19_ADDR                   0x0000044eU
#define MSR_IA32_MC19_MISC                   0x0000044fU
#define MSR_IA32_MC20_CTL                    0x00000450U
#define MSR_IA32_MC20_STATUS                 0x00000451U
#define MSR_IA32_MC20_ADDR                   0x00000452U
#define MSR_IA32_MC20_MISC                   0x00000453U
#define MSR_IA32_MC21_CTL                    0x00000454U
#define MSR_IA32_MC21_STATUS                 0x00000455U
#define MSR_IA32_MC21_ADDR                   0x00000456U
#define MSR_IA32_MC21_MISC                   0x00000457U
#define MSR_IA32_MC22_CTL                    0x00000458U
#define MSR_IA32_MC22_STATUS                 0x00000459U
#define MSR_IA32_MC22_ADDR                   0x0000045aU
#define MSR_IA32_MC22_MISC                   0x0000045bU
#define MSR_IA32_MC23_CTL                    0x0000045cU
#define MSR_IA32_MC23_STATUS                 0x0000045dU
#define MSR_IA32_MC23_ADDR                   0x0000045eU
#define MSR_IA32_MC23_MISC                   0x0000045fU
#define MSR_IA32_MC24_CTL                    0x00000460U
#define MSR_IA32_MC24_STATUS                 0x00000461U
#define MSR_IA32_MC24_ADDR                   0x00000462U
#define MSR_IA32_MC24_MISC                   0x00000463U
#define MSR_IA32_MC25_CTL                    0x00000464U
#define MSR_IA32_MC25_STATUS                 0x00000465U
#define MSR_IA32_MC25_ADDR                   0x00000466U
#define MSR_IA32_MC25_MISC                   0x00000467U
#define MSR_IA32_MC26_CTL                    0x00000468U
#define MSR_IA32_MC26_STATUS                 0x00000469U
#define MSR_IA32_MC26_ADDR                   0x0000046aU
#define MSR_IA32_MC26_MISC                   0x0000046bU
#define MSR_IA32_MC27_CTL                    0x0000046cU
#define MSR_IA32_MC27_STATUS                 0x0000046dU
#define MSR_IA32_MC27_ADDR                   0x0000046eU
#define MSR_IA32_MC27_MISC                   0x0000046fU
#define MSR_IA32_MC28_CTL                    0x00000470U
#define MSR_IA32_MC28_STATUS                 0x00000471U
#define MSR_IA32_MC28_ADDR                   0x00000472U
#define MSR_IA32_MC28_MISC                   0x00000473U
#define MSR_IA32_VMX_BASIC                   0x00000480U
#define MSR_IA32_VMX_PINBASED_CTLS           0x00000481U
#define MSR_IA32_VMX_PROCBASED_CTLS          0x00000482U
#define MSR_IA32_VMX_EXIT_CTLS               0x00000483U
#define MSR_IA32_VMX_ENTRY_CTLS              0x00000484U
#define MSR_IA32_VMX_MISC                    0x00000485U
#define MSR_IA32_VMX_CR0_FIXED0              0x00000486U
#define MSR_IA32_VMX_CR0_FIXED1              0x00000487U
#define MSR_IA32_VMX_CR4_FIXED0              0x00000488U
#define MSR_IA32_VMX_CR4_FIXED1              0x00000489U
#define MSR_IA32_VMX_VMCS_ENUM               0x0000048aU
#define MSR_IA32_VMX_PROCBASED_CTLS2         0x0000048bU
#define MSR_IA32_VMX_EPT_VPID_CAP            0x0000048cU
#define MSR_IA32_VMX_TRUE_PINBASED_CTLS      0x0000048dU
#define MSR_IA32_VMX_TRUE_PROCBASED_CTLS     0x0000048eU
#define MSR_IA32_VMX_TRUE_EXIT_CTLS          0x0000048fU
#define MSR_IA32_VMX_TRUE_ENTRY_CTLS         0x00000490U
#define MSR_IA32_VMX_VMFUNC                  0x00000491U
#define MSR_IA32_A_PMC0                      0x000004c1U
#define MSR_IA32_A_PMC1                      0x000004c2U
#define MSR_IA32_A_PMC2                      0x000004c3U
#define MSR_IA32_A_PMC3                      0x000004c4U
#define MSR_IA32_A_PMC4                      0x000004c5U
#define MSR_IA32_A_PMC5                      0x000004c6U
#define MSR_IA32_A_PMC6                      0x000004c7U
#define MSR_IA32_A_PMC7                      0x000004c8U
#define MSR_IA32_MCG_EXT_CTL                 0x000004d0U
#define MSR_IA32_SGX_SVN_STATUS              0x00000500U
#define MSR_IA32_RTIT_OUTPUT_BASE            0x00000560U
#define MSR_IA32_RTIT_OUTPUT_MASK_PTRS       0x00000561U
#define MSR_IA32_RTIT_CTL                    0x00000570U
#define MSR_IA32_RTIT_STATUS                 0x00000571U
#define MSR_IA32_RTIT_CR3_MATCH              0x00000572U
#define MSR_IA32_RTIT_ADDR0_A                0x00000580U
#define MSR_IA32_RTIT_ADDR0_B                0x00000581U
#define MSR_IA32_RTIT_ADDR1_A                0x00000582U
#define MSR_IA32_RTIT_ADDR1_B                0x00000583U
#define MSR_IA32_RTIT_ADDR2_A                0x00000584U
#define MSR_IA32_RTIT_ADDR2_B                0x00000585U
#define MSR_IA32_RTIT_ADDR3_A                0x00000586U
#define MSR_IA32_RTIT_ADDR3_B                0x00000587U
#define MSR_IA32_DS_AREA                     0x00000600U
#define MSR_IA32_TSC_DEADLINE                0x000006e0U
#define MSR_IA32_PM_ENABLE                   0x00000770U
#define MSR_IA32_HWP_CAPABILITIES            0x00000771U
#define MSR_IA32_HWP_REQUEST_PKG             0x00000772U
#define MSR_IA32_HWP_INTERRUPT               0x00000773U
#define MSR_IA32_HWP_REQUEST                 0x00000774U
#define MSR_IA32_HWP_STATUS                  0x00000777U
#define MSR_IA32_X2APIC_APICID               0x00000802U
#define MSR_IA32_X2APIC_VERSION              0x00000803U
#define MSR_IA32_X2APIC_TPR                  0x00000808U
#define MSR_IA32_X2APIC_PPR                  0x0000080aU
#define MSR_IA32_X2APIC_EOI                  0x0000080bU
#define MSR_IA32_X2APIC_LDR                  0x0000080dU
#define MSR_IA32_X2APIC_SIVR                 0x0000080fU
#define MSR_IA32_X2APIC_ISR0                 0x00000810U
#define MSR_IA32_X2APIC_ISR1                 0x00000811U
#define MSR_IA32_X2APIC_ISR2                 0x00000812U
#define MSR_IA32_X2APIC_ISR3                 0x00000813U
#define MSR_IA32_X2APIC_ISR4                 0x00000814U
#define MSR_IA32_X2APIC_ISR5                 0x00000815U
#define MSR_IA32_X2APIC_ISR6                 0x00000816U
#define MSR_IA32_X2APIC_ISR7                 0x00000817U
#define MSR_IA32_X2APIC_TMR0                 0x00000818U
#define MSR_IA32_X2APIC_TMR1                 0x00000819U
#define MSR_IA32_X2APIC_TMR2                 0x0000081aU
#define MSR_IA32_X2APIC_TMR3                 0x0000081bU
#define MSR_IA32_X2APIC_TMR4                 0x0000081cU
#define MSR_IA32_X2APIC_TMR5                 0x0000081dU
#define MSR_IA32_X2APIC_TMR6                 0x0000081eU
#define MSR_IA32_X2APIC_TMR7                 0x0000081fU
#define MSR_IA32_X2APIC_IRR0                 0x00000820U
#define MSR_IA32_X2APIC_IRR1                 0x00000821U
#define MSR_IA32_X2APIC_IRR2                 0x00000822U
#define MSR_IA32_X2APIC_IRR3                 0x00000823U
#define MSR_IA32_X2APIC_IRR4                 0x00000824U
#define MSR_IA32_X2APIC_IRR5                 0x00000825U
#define MSR_IA32_X2APIC_IRR6                 0x00000826U
#define MSR_IA32_X2APIC_IRR7                 0x00000827U
#define MSR_IA32_X2APIC_ESR                  0x00000828U
#define MSR_IA32_X2APIC_LVT_CMCI             0x0000082fU
#define MSR_IA32_X2APIC_ICR                  0x00000830U
#define MSR_IA32_X2APIC_LVT_TIMER            0x00000832U
#define MSR_IA32_X2APIC_LVT_THERMAL          0x00000833U
#define MSR_IA32_X2APIC_LVT_PMI              0x00000834U
#define MSR_IA32_X2APIC_LVT_LINT0            0x00000835U
#define MSR_IA32_X2APIC_LVT_LINT1            0x00000836U
#define MSR_IA32_X2APIC_LVT_ERROR            0x00000837U
#define MSR_IA32_X2APIC_INIT_COUNT           0x00000838U
#define MSR_IA32_X2APIC_CUR_COUNT            0x00000839U
#define MSR_IA32_X2APIC_DIV_CONF             0x0000083eU
#define MSR_IA32_X2APIC_SELF_IPI             0x0000083fU
#define MSR_IA32_DEBUG_INTERFACE             0x00000c80U
#define MSR_IA32_L3_QOS_CFG                  0x00000c81U
#define MSR_IA32_QM_EVTSEL                   0x00000c8dU
#define MSR_IA32_QM_CTR                      0x00000c8eU
#define MSR_IA32_PQR_ASSOC                   0x00000c8fU
#define MSR_IA32_L3_MASK_0                   0x00000c90U
#define MSR_IA32_L2_MASK_0                   0x00000d10U
#define MSR_IA32_BNDCFGS                     0x00000d90U
#define MSR_IA32_XSS                         0x00000da0U
#define MSR_IA32_PKG_HDC_CTL                 0x00000db0U
#define MSR_IA32_PM_CTL1                     0x00000db1U
#define MSR_IA32_THREAD_STALL                0x00000db2U
#define MSR_IA32_EFER                        0xc0000080U
#define MSR_IA32_STAR                        0xc0000081U
#define MSR_IA32_LSTAR                       0xc0000082U
#define MSR_IA32_FMASK                       0xc0000084U
#define MSR_IA32_FS_BASE                     0xc0000100U
#define MSR_IA32_GS_BASE                     0xc0000101U
#define MSR_IA32_KERNEL_GS_BASE              0xc0000102U
#define MSR_IA32_TSC_AUX                     0xc0000103U



/*
 * 35.2 MSRS IN THE INTEL CORE 2 PROCESSOR FAMILY
 */
#define MSR_PLATFORM_ID             0x00000017U
#define MSR_EBL_CR_POWERON          0x0000002aU
#define MSR_FEATURE_CONTROL         0x0000003aU
#define MSR_LASTBRANCH_0_FROM_IP    0x00000040U
#define MSR_LASTBRANCH_1_FROM_IP    0x00000041U
#define MSR_LASTBRANCH_2_FROM_IP    0x00000042U
#define MSR_LASTBRANCH_3_FROM_IP    0x00000043U
#define MSR_LASTBRANCH_0_TO_IP      0x00000060U
#define MSR_LASTBRANCH_1_TO_IP      0x00000061U
#define MSR_LASTBRANCH_2_TO_IP      0x00000062U
#define MSR_LASTBRANCH_3_TO_IP      0x00000063U
#define MSR_SMRR_PHYSBASE           0x000000a0U
#define MSR_SMRR_PHYSMASK           0x000000a1U
#define MSR_FSB_FREQ                0x000000cdU
#define MSR_BBL_CR_CTL3             0x0000011eU
#define MSR_PERF_STATUS             0x00000198U
#define MSR_THERM2_CTL              0x0000019dU
#define MSR_LASTBRANCH_TOS          0x000001c9U
#define MSR_LER_FROM_LIP            0x000001ddU
#define MSR_LER_TO_LIP              0x000001deU
#define MSR_PERF_FIXED_CTR0         0x00000309U
#define MSR_PERF_FIXED_CTR1         0x0000030aU
#define MSR_PERF_FIXED_CTR2         0x0000030bU
#define MSR_PERF_CAPABILITIES       0x00000345U
#define MSR_PERF_FIXED_CTR_CTRL     0x0000038dU
#define MSR_PERF_GLOBAL_STATUS      0x0000038eU
#define MSR_PERF_GLOBAL_CTRL        0x0000038fU
#define MSR_PERF_GLOBAL_OVF_CTRL    0x00000390U
#define MSR_PEBS_ENABLE             0x000003f1U



/*
 * 35.3 MSRS IN THE 45 NM AND 32 NM INTEL ATOM PROCESSOR FAMILY
 */
#define MSR_LASTBRANCH_4_FROM_IP    0x00000044U
#define MSR_LASTBRANCH_5_FROM_IP    0x00000045U
#define MSR_LASTBRANCH_6_FROM_IP    0x00000046U
#define MSR_LASTBRANCH_7_FROM_IP    0x00000047U
#define MSR_LASTBRANCH_4_TO_IP      0x00000064U
#define MSR_LASTBRANCH_5_TO_IP      0x00000065U
#define MSR_LASTBRANCH_6_TO_IP      0x00000066U
#define MSR_LASTBRANCH_7_TO_IP      0x00000067U
#define MSR_PKG_C2_RESIDENCY        0x000003f8U
#define MSR_PKG_C4_RESIDENCY        0x000003f9U



/*
 * 35.4 MSRS IN INTEL PROCESSORS BASED ON SILVERMONT MICROARCHITECTURE
 */
#define MSR_PKG_C6_RESIDENCY              0x000003faU
#define MSR_SMI_COUNT                     0x00000034U
#define MSR_PMG_IO_CAPTURE_BASE           0x000000e4U
#define MSR_FEATURE_CONFIG                0x0000013cU
#define MSR_TEMPERATURE_TARGET            0x000001a2U
#define MSR_OFFCORE_RSP_0                 0x000001a6U
#define MSR_OFFCORE_RSP_1                 0x000001a7U
#define MSR_CORE_C6_RESIDENCY             0x000003fdU
#define MSR_IA32_VMX_EPT_VPID_ENUM        0x0000048cU
#define MSR_IA32_VMX_FMFUNC               0x00000491U
#define MSR_CORE_C1_RESIDENCY             0x00000660U
#define MSR_PKG_CST_CONFIG_CONTROL        0x000000e2U
#define MSR_LBR_SELECT                    0x000001c8U
#define MSR_MC6_RESIDENCY_COUNTER         0x00000664U
#define MSR_RAPL_POWER_UNIT               0x00000606U
#define MSR_PKG_POWER_LIMIT               0x00000610U
#define MSR_PKG_ENERGY_STATUS             0x00000611U
#define MSR_PP0_ENERGY_STATUS             0x00000639U
#define MSR_CC6_DEMOTION_POLICY_CONFIG    0x00000668U
#define MSR_MC6_DEMOTION_POLICY_CONFIG    0x00000669U
#define MSR_MISC_FEATURE_CONTROL          0x000001a4U
#define MSR_TURBO_RATIO_LIMIT             0x000001adU
#define MSR_PKG_POWER_INFO                0x0000066eU



/*
 * 35.5 MSRS IN NEXT GENERATION INTEL ATOM PROCESSORS
 */
#define MSR_PP0_POWER_LIMIT            0x00000638U
#define MSR_PLATFORM_INFO              0x000000ceU
#define MSR_SMM_MCA_CAP                0x0000017dU
#define MSR_MISC_PWR_MGMT              0x000001aaU
#define MSR_TURBO_GROUP_CORECNT        0x000001aeU
#define MSR_POWER_CTL                  0x000001fcU
#define MSR_SGXOWNER0                  0x00000300U
#define MSR_SGXOWNER1                  0x00000301U
#define MSR_PKG_C3_RESIDENCY           0x000003f8U
#define MSR_CORE_C3_RESIDENCY          0x000003fcU
#define MSR_SMM_FEATURE_CONTROL        0x000004e0U
#define MSR_SMM_DELAYED                0x000004e2U
#define MSR_SMM_BLOCKED                0x000004e3U
#define MSR_PKGC3_IRTL                 0x0000060aU
#define MSR_PKGC_IRTL1                 0x0000060bU
#define MSR_PKGC_IRTL2                 0x0000060cU
#define MSR_PKG_PERF_STATUS            0x00000613U
#define MSR_DRAM_POWER_LIMIT           0x00000618U
#define MSR_DRAM_ENERGY_STATUS         0x00000619U
#define MSR_DRAM_PERF_STATUS           0x0000061bU
#define MSR_DRAM_POWER_INFO            0x0000061cU
#define MSR_PKG_C10_RESIDENCY          0x00000632U
#define MSR_PP1_ENERGY_STATUS          0x00000641U
#define MSR_TURBO_ACTIVATION_RATIO     0x0000064cU
#define MSR_CORE_PERF_LIMIT_REASONS    0x0000064fU
#define MSR_LASTBRANCH_8_FROM_IP       0x00000688U
#define MSR_LASTBRANCH_9_FROM_IP       0x00000689U
#define MSR_LASTBRANCH_10_FROM_IP      0x0000068aU
#define MSR_LASTBRANCH_11_FROM_IP      0x0000068bU
#define MSR_LASTBRANCH_12_FROM_IP      0x0000068cU
#define MSR_LASTBRANCH_13_FROM_IP      0x0000068dU
#define MSR_LASTBRANCH_14_FROM_IP      0x0000068eU
#define MSR_LASTBRANCH_15_FROM_IP      0x0000068fU
#define MSR_LASTBRANCH_16_FROM_IP      0x00000690U
#define MSR_LASTBRANCH_17_FROM_IP      0x00000691U
#define MSR_LASTBRANCH_18_FROM_IP      0x00000692U
#define MSR_LASTBRANCH_19_FROM_IP      0x00000693U
#define MSR_LASTBRANCH_20_FROM_IP      0x00000694U
#define MSR_LASTBRANCH_21_FROM_IP      0x00000695U
#define MSR_LASTBRANCH_22_FROM_IP      0x00000696U
#define MSR_LASTBRANCH_23_FROM_IP      0x00000697U
#define MSR_LASTBRANCH_24_FROM_IP      0x00000698U
#define MSR_LASTBRANCH_25_FROM_IP      0x00000699U
#define MSR_LASTBRANCH_26_FROM_IP      0x0000069aU
#define MSR_LASTBRANCH_27_FROM_IP      0x0000069bU
#define MSR_LASTBRANCH_28_FROM_IP      0x0000069cU
#define MSR_LASTBRANCH_29_FROM_IP      0x0000069dU
#define MSR_LASTBRANCH_30_FROM_IP      0x0000069eU
#define MSR_LASTBRANCH_31_FROM_IP      0x0000069fU
#define MSR_LASTBRANCH_8_TO_IP         0x000006c8U
#define MSR_LASTBRANCH_9_TO_IP         0x000006c9U
#define MSR_LASTBRANCH_10_TO_IP        0x000006caU
#define MSR_LASTBRANCH_11_TO_IP        0x000006cbU
#define MSR_LASTBRANCH_12_TO_IP        0x000006ccU
#define MSR_LASTBRANCH_13_TO_IP        0x000006cdU
#define MSR_LASTBRANCH_14_TO_IP        0x000006ceU
#define MSR_LASTBRANCH_15_TO_IP        0x000006cfU
#define MSR_LASTBRANCH_16_TO_IP        0x000006d0U
#define MSR_LASTBRANCH_17_TO_IP        0x000006d1U
#define MSR_LASTBRANCH_18_TO_IP        0x000006d2U
#define MSR_LASTBRANCH_19_TO_IP        0x000006d3U
#define MSR_LASTBRANCH_20_TO_IP        0x000006d4U
#define MSR_LASTBRANCH_21_TO_IP        0x000006d5U
#define MSR_LASTBRANCH_22_TO_IP        0x000006d6U
#define MSR_LASTBRANCH_23_TO_IP        0x000006d7U
#define MSR_LASTBRANCH_24_TO_IP        0x000006d8U
#define MSR_LASTBRANCH_25_TO_IP        0x000006d9U
#define MSR_LASTBRANCH_26_TO_IP        0x000006daU
#define MSR_LASTBRANCH_27_TO_IP        0x000006dbU
#define MSR_LASTBRANCH_28_TO_IP        0x000006dcU
#define MSR_LASTBRANCH_29_TO_IP        0x000006ddU
#define MSR_LASTBRANCH_30_TO_IP        0x000006deU
#define MSR_LASTBRANCH_31_TO_IP        0x000006dfU



/*
 * 35.6 MSRS IN THE INTEL MICROARCHITECTURE CODE NAME NEHALEM
 */
#define MSR_IA32_L2_QOS_MASK_0             0x00000d10U
#define MSR_IA32_L2_QOS_MASK_1             0x00000d11U
#define MSR_IA32_L2_QOS_MASK_2             0x00000d12U
#define MSR_IA32_L2_QOS_MASK_3             0x00000d13U
#define MSR_TURBO_POWER_CURRENT_LIMIT      0x000001acU
#define MSR_PEBS_LD_LAT                    0x000003f6U
#define MSR_PKG_C7_RESIDENCY               0x000003faU
#define MSR_GQ_SNOOP_MESF                  0x00000301U
#define MSR_UNCORE_PERF_GLOBAL_CTRL        0x00000391U
#define MSR_UNCORE_PERF_GLOBAL_STATUS      0x00000392U
#define MSR_UNCORE_PERF_GLOBAL_OVF_CTRL    0x00000393U
#define MSR_UNCORE_FIXED_CTR0              0x00000394U
#define MSR_UNCORE_FIXED_CTR_CTRL          0x00000395U
#define MSR_UNCORE_ADDR_OPCODE_MATCH       0x00000396U
#define MSR_UNCORE_PMC0                    0x000003b0U
#define MSR_UNCORE_PMC1                    0x000003b1U
#define MSR_UNCORE_PMC2                    0x000003b2U
#define MSR_UNCORE_PMC3                    0x000003b3U
#define MSR_UNCORE_PMC4                    0x000003b4U
#define MSR_UNCORE_PMC5                    0x000003b5U
#define MSR_UNCORE_PMC6                    0x000003b6U
#define MSR_UNCORE_PMC7                    0x000003b7U
#define MSR_UNCORE_PERFEVTSEL0             0x000003c0U
#define MSR_UNCORE_PERFEVTSEL1             0x000003c1U
#define MSR_UNCORE_PERFEVTSEL2             0x000003c2U
#define MSR_UNCORE_PERFEVTSEL3             0x000003c3U
#define MSR_UNCORE_PERFEVTSEL4             0x000003c4U
#define MSR_UNCORE_PERFEVTSEL5             0x000003c5U
#define MSR_UNCORE_PERFEVTSEL6             0x000003c6U
#define MSR_UNCORE_PERFEVTSEL7             0x000003c7U
#define MSR_W_PMON_FIXED_CTR               0x00000394U
#define MSR_W_PMON_FIXED_CTR_CTL           0x00000395U
#define MSR_U_PMON_GLOBAL_CTRL             0x00000c00U
#define MSR_U_PMON_GLOBAL_STATUS           0x00000c01U
#define MSR_U_PMON_GLOBAL_OVF_CTRL         0x00000c02U
#define MSR_U_PMON_EVNT_SEL                0x00000c10U
#define MSR_U_PMON_CTR                     0x00000c11U
#define MSR_B0_PMON_BOX_CTRL               0x00000c20U
#define MSR_B0_PMON_BOX_STATUS             0x00000c21U
#define MSR_B0_PMON_BOX_OVF_CTRL           0x00000c22U
#define MSR_B0_PMON_EVNT_SEL0              0x00000c30U
#define MSR_B0_PMON_CTR0                   0x00000c31U
#define MSR_B0_PMON_EVNT_SEL1              0x00000c32U
#define MSR_B0_PMON_CTR1                   0x00000c33U
#define MSR_B0_PMON_EVNT_SEL2              0x00000c34U
#define MSR_B0_PMON_CTR2                   0x00000c35U
#define MSR_B0_PMON_EVNT_SEL3              0x00000c36U
#define MSR_B0_PMON_CTR3                   0x00000c37U
#define MSR_S0_PMON_BOX_CTRL               0x00000c40U
#define MSR_S0_PMON_BOX_STATUS             0x00000c41U
#define MSR_S0_PMON_BOX_OVF_CTRL           0x00000c42U
#define MSR_S0_PMON_EVNT_SEL0              0x00000c50U
#define MSR_S0_PMON_CTR0                   0x00000c51U
#define MSR_S0_PMON_EVNT_SEL1              0x00000c52U
#define MSR_S0_PMON_CTR1                   0x00000c53U
#define MSR_S0_PMON_EVNT_SEL2              0x00000c54U
#define MSR_S0_PMON_CTR2                   0x00000c55U
#define MSR_S0_PMON_EVNT_SEL3              0x00000c56U
#define MSR_S0_PMON_CTR3                   0x00000c57U
#define MSR_B1_PMON_BOX_CTRL               0x00000c60U
#define MSR_B1_PMON_BOX_STATUS             0x00000c61U
#define MSR_B1_PMON_BOX_OVF_CTRL           0x00000c62U
#define MSR_B1_PMON_EVNT_SEL0              0x00000c70U
#define MSR_B1_PMON_CTR0                   0x00000c71U
#define MSR_B1_PMON_EVNT_SEL1              0x00000c72U
#define MSR_B1_PMON_CTR1                   0x00000c73U
#define MSR_B1_PMON_EVNT_SEL2              0x00000c74U
#define MSR_B1_PMON_CTR2                   0x00000c75U
#define MSR_B1_PMON_EVNT_SEL3              0x00000c76U
#define MSR_B1_PMON_CTR3                   0x00000c77U
#define MSR_W_PMON_BOX_CTRL                0x00000c80U
#define MSR_W_PMON_BOX_STATUS              0x00000c81U
#define MSR_W_PMON_BOX_OVF_CTRL            0x00000c82U
#define MSR_W_PMON_EVNT_SEL0               0x00000c90U
#define MSR_W_PMON_CTR0                    0x00000c91U
#define MSR_W_PMON_EVNT_SEL1               0x00000c92U
#define MSR_W_PMON_CTR1                    0x00000c93U
#define MSR_W_PMON_EVNT_SEL2               0x00000c94U
#define MSR_W_PMON_CTR2                    0x00000c95U
#define MSR_W_PMON_EVNT_SEL3               0x00000c96U
#define MSR_W_PMON_CTR3                    0x00000c97U
#define MSR_M0_PMON_BOX_CTRL               0x00000ca0U
#define MSR_M0_PMON_BOX_STATUS             0x00000ca1U
#define MSR_M0_PMON_BOX_OVF_CTRL           0x00000ca2U
#define MSR_M0_PMON_TIMESTAMP              0x00000ca4U
#define MSR_M0_PMON_DSP                    0x00000ca5U
#define MSR_M0_PMON_ISS                    0x00000ca6U
#define MSR_M0_PMON_MAP                    0x00000ca7U
#define MSR_M0_PMON_MSC_THR                0x00000ca8U
#define MSR_M0_PMON_PGT                    0x00000ca9U
#define MSR_M0_PMON_PLD                    0x00000caaU
#define MSR_M0_PMON_ZDP                    0x00000cabU
#define MSR_M0_PMON_EVNT_SEL0              0x00000cb0U
#define MSR_M0_PMON_CTR0                   0x00000cb1U
#define MSR_M0_PMON_EVNT_SEL1              0x00000cb2U
#define MSR_M0_PMON_CTR1                   0x00000cb3U
#define MSR_M0_PMON_EVNT_SEL2              0x00000cb4U
#define MSR_M0_PMON_CTR2                   0x00000cb5U
#define MSR_M0_PMON_EVNT_SEL3              0x00000cb6U
#define MSR_M0_PMON_CTR3                   0x00000cb7U
#define MSR_M0_PMON_EVNT_SEL4              0x00000cb8U
#define MSR_M0_PMON_CTR4                   0x00000cb9U
#define MSR_M0_PMON_EVNT_SEL5              0x00000cbaU
#define MSR_M0_PMON_CTR5                   0x00000cbbU
#define MSR_S1_PMON_BOX_CTRL               0x00000cc0U
#define MSR_S1_PMON_BOX_STATUS             0x00000cc1U
#define MSR_S1_PMON_BOX_OVF_CTRL           0x00000cc2U
#define MSR_S1_PMON_EVNT_SEL0              0x00000cd0U
#define MSR_S1_PMON_CTR0                   0x00000cd1U
#define MSR_S1_PMON_EVNT_SEL1              0x00000cd2U
#define MSR_S1_PMON_CTR1                   0x00000cd3U
#define MSR_S1_PMON_EVNT_SEL2              0x00000cd4U
#define MSR_S1_PMON_CTR2                   0x00000cd5U
#define MSR_S1_PMON_EVNT_SEL3              0x00000cd6U
#define MSR_S1_PMON_CTR3                   0x00000cd7U
#define MSR_M1_PMON_BOX_CTRL               0x00000ce0U
#define MSR_M1_PMON_BOX_STATUS             0x00000ce1U
#define MSR_M1_PMON_BOX_OVF_CTRL           0x00000ce2U
#define MSR_M1_PMON_TIMESTAMP              0x00000ce4U
#define MSR_M1_PMON_DSP                    0x00000ce5U
#define MSR_M1_PMON_ISS                    0x00000ce6U
#define MSR_M1_PMON_MAP                    0x00000ce7U
#define MSR_M1_PMON_MSC_THR                0x00000ce8U
#define MSR_M1_PMON_PGT                    0x00000ce9U
#define MSR_M1_PMON_PLD                    0x00000ceaU
#define MSR_M1_PMON_ZDP                    0x00000cebU
#define MSR_M1_PMON_EVNT_SEL0              0x00000cf0U
#define MSR_M1_PMON_CTR0                   0x00000cf1U
#define MSR_M1_PMON_EVNT_SEL1              0x00000cf2U
#define MSR_M1_PMON_CTR1                   0x00000cf3U
#define MSR_M1_PMON_EVNT_SEL2              0x00000cf4U
#define MSR_M1_PMON_CTR2                   0x00000cf5U
#define MSR_M1_PMON_EVNT_SEL3              0x00000cf6U
#define MSR_M1_PMON_CTR3                   0x00000cf7U
#define MSR_M1_PMON_EVNT_SEL4              0x00000cf8U
#define MSR_M1_PMON_CTR4                   0x00000cf9U
#define MSR_M1_PMON_EVNT_SEL5              0x00000cfaU
#define MSR_M1_PMON_CTR5                   0x00000cfbU
#define MSR_C0_PMON_BOX_CTRL               0x00000d00U
#define MSR_C0_PMON_BOX_STATUS             0x00000d01U
#define MSR_C0_PMON_BOX_OVF_CTRL           0x00000d02U
#define MSR_C0_PMON_EVNT_SEL0              0x00000d10U
#define MSR_C0_PMON_CTR0                   0x00000d11U
#define MSR_C0_PMON_EVNT_SEL1              0x00000d12U
#define MSR_C0_PMON_CTR1                   0x00000d13U
#define MSR_C0_PMON_EVNT_SEL2              0x00000d14U
#define MSR_C0_PMON_CTR2                   0x00000d15U
#define MSR_C0_PMON_EVNT_SEL3              0x00000d16U
#define MSR_C0_PMON_CTR3                   0x00000d17U
#define MSR_C0_PMON_EVNT_SEL4              0x00000d18U
#define MSR_C0_PMON_CTR4                   0x00000d19U
#define MSR_C0_PMON_EVNT_SEL5              0x00000d1aU
#define MSR_C0_PMON_CTR5                   0x00000d1bU
#define MSR_C4_PMON_BOX_CTRL               0x00000d20U
#define MSR_C4_PMON_BOX_STATUS             0x00000d21U
#define MSR_C4_PMON_BOX_OVF_CTRL           0x00000d22U
#define MSR_C4_PMON_EVNT_SEL0              0x00000d30U
#define MSR_C4_PMON_CTR0                   0x00000d31U
#define MSR_C4_PMON_EVNT_SEL1              0x00000d32U
#define MSR_C4_PMON_CTR1                   0x00000d33U
#define MSR_C4_PMON_EVNT_SEL2              0x00000d34U
#define MSR_C4_PMON_CTR2                   0x00000d35U
#define MSR_C4_PMON_EVNT_SEL3              0x00000d36U
#define MSR_C4_PMON_CTR3                   0x00000d37U
#define MSR_C4_PMON_EVNT_SEL4              0x00000d38U
#define MSR_C4_PMON_CTR4                   0x00000d39U
#define MSR_C4_PMON_EVNT_SEL5              0x00000d3aU
#define MSR_C4_PMON_CTR5                   0x00000d3bU
#define MSR_C2_PMON_BOX_CTRL               0x00000d40U
#define MSR_C2_PMON_BOX_STATUS             0x00000d41U
#define MSR_C2_PMON_BOX_OVF_CTRL           0x00000d42U
#define MSR_C2_PMON_EVNT_SEL0              0x00000d50U
#define MSR_C2_PMON_CTR0                   0x00000d51U
#define MSR_C2_PMON_EVNT_SEL1              0x00000d52U
#define MSR_C2_PMON_CTR1                   0x00000d53U
#define MSR_C2_PMON_EVNT_SEL2              0x00000d54U
#define MSR_C2_PMON_CTR2                   0x00000d55U
#define MSR_C2_PMON_EVNT_SEL3              0x00000d56U
#define MSR_C2_PMON_CTR3                   0x00000d57U
#define MSR_C2_PMON_EVNT_SEL4              0x00000d58U
#define MSR_C2_PMON_CTR4                   0x00000d59U
#define MSR_C2_PMON_EVNT_SEL5              0x00000d5aU
#define MSR_C2_PMON_CTR5                   0x00000d5bU
#define MSR_C6_PMON_BOX_CTRL               0x00000d60U
#define MSR_C6_PMON_BOX_STATUS             0x00000d61U
#define MSR_C6_PMON_BOX_OVF_CTRL           0x00000d62U
#define MSR_C6_PMON_EVNT_SEL0              0x00000d70U
#define MSR_C6_PMON_CTR0                   0x00000d71U
#define MSR_C6_PMON_EVNT_SEL1              0x00000d72U
#define MSR_C6_PMON_CTR1                   0x00000d73U
#define MSR_C6_PMON_EVNT_SEL2              0x00000d74U
#define MSR_C6_PMON_CTR2                   0x00000d75U
#define MSR_C6_PMON_EVNT_SEL3              0x00000d76U
#define MSR_C6_PMON_CTR3                   0x00000d77U
#define MSR_C6_PMON_EVNT_SEL4              0x00000d78U
#define MSR_C6_PMON_CTR4                   0x00000d79U
#define MSR_C6_PMON_EVNT_SEL5              0x00000d7aU
#define MSR_C6_PMON_CTR5                   0x00000d7bU
#define MSR_C1_PMON_BOX_CTRL               0x00000d80U
#define MSR_C1_PMON_BOX_STATUS             0x00000d81U
#define MSR_C1_PMON_BOX_OVF_CTRL           0x00000d82U
#define MSR_C1_PMON_EVNT_SEL0              0x00000d90U
#define MSR_C1_PMON_CTR0                   0x00000d91U
#define MSR_C1_PMON_EVNT_SEL1              0x00000d92U
#define MSR_C1_PMON_CTR1                   0x00000d93U
#define MSR_C1_PMON_EVNT_SEL2              0x00000d94U
#define MSR_C1_PMON_CTR2                   0x00000d95U
#define MSR_C1_PMON_EVNT_SEL3              0x00000d96U
#define MSR_C1_PMON_CTR3                   0x00000d97U
#define MSR_C1_PMON_EVNT_SEL4              0x00000d98U
#define MSR_C1_PMON_CTR4                   0x00000d99U
#define MSR_C1_PMON_EVNT_SEL5              0x00000d9aU
#define MSR_C1_PMON_CTR5                   0x00000d9bU
#define MSR_C5_PMON_BOX_CTRL               0x00000da0U
#define MSR_C5_PMON_BOX_STATUS             0x00000da1U
#define MSR_C5_PMON_BOX_OVF_CTRL           0x00000da2U
#define MSR_C5_PMON_EVNT_SEL0              0x00000db0U
#define MSR_C5_PMON_CTR0                   0x00000db1U
#define MSR_C5_PMON_EVNT_SEL1              0x00000db2U
#define MSR_C5_PMON_CTR1                   0x00000db3U
#define MSR_C5_PMON_EVNT_SEL2              0x00000db4U
#define MSR_C5_PMON_CTR2                   0x00000db5U
#define MSR_C5_PMON_EVNT_SEL3              0x00000db6U
#define MSR_C5_PMON_CTR3                   0x00000db7U
#define MSR_C5_PMON_EVNT_SEL4              0x00000db8U
#define MSR_C5_PMON_CTR4                   0x00000db9U
#define MSR_C5_PMON_EVNT_SEL5              0x00000dbaU
#define MSR_C5_PMON_CTR5                   0x00000dbbU
#define MSR_C3_PMON_BOX_CTRL               0x00000dc0U
#define MSR_C3_PMON_BOX_STATUS             0x00000dc1U
#define MSR_C3_PMON_BOX_OVF_CTRL           0x00000dc2U
#define MSR_C3_PMON_EVNT_SEL0              0x00000dd0U
#define MSR_C3_PMON_CTR0                   0x00000dd1U
#define MSR_C3_PMON_EVNT_SEL1              0x00000dd2U
#define MSR_C3_PMON_CTR1                   0x00000dd3U
#define MSR_C3_PMON_EVNT_SEL2              0x00000dd4U
#define MSR_C3_PMON_CTR2                   0x00000dd5U
#define MSR_C3_PMON_EVNT_SEL3              0x00000dd6U
#define MSR_C3_PMON_CTR3                   0x00000dd7U
#define MSR_C3_PMON_EVNT_SEL4              0x00000dd8U
#define MSR_C3_PMON_CTR4                   0x00000dd9U
#define MSR_C3_PMON_EVNT_SEL5              0x00000ddaU
#define MSR_C3_PMON_CTR5                   0x00000ddbU
#define MSR_C7_PMON_BOX_CTRL               0x00000de0U
#define MSR_C7_PMON_BOX_STATUS             0x00000de1U
#define MSR_C7_PMON_BOX_OVF_CTRL           0x00000de2U
#define MSR_C7_PMON_EVNT_SEL0              0x00000df0U
#define MSR_C7_PMON_CTR0                   0x00000df1U
#define MSR_C7_PMON_EVNT_SEL1              0x00000df2U
#define MSR_C7_PMON_CTR1                   0x00000df3U
#define MSR_C7_PMON_EVNT_SEL2              0x00000df4U
#define MSR_C7_PMON_CTR2                   0x00000df5U
#define MSR_C7_PMON_EVNT_SEL3              0x00000df6U
#define MSR_C7_PMON_CTR3                   0x00000df7U
#define MSR_C7_PMON_EVNT_SEL4              0x00000df8U
#define MSR_C7_PMON_CTR4                   0x00000df9U
#define MSR_C7_PMON_EVNT_SEL5              0x00000dfaU
#define MSR_C7_PMON_CTR5                   0x00000dfbU
#define MSR_R0_PMON_BOX_CTRL               0x00000e00U
#define MSR_R0_PMON_BOX_STATUS             0x00000e01U
#define MSR_R0_PMON_BOX_OVF_CTRL           0x00000e02U
#define MSR_R0_PMON_IPERF0_P0              0x00000e04U
#define MSR_R0_PMON_IPERF0_P1              0x00000e05U
#define MSR_R0_PMON_IPERF0_P2              0x00000e06U
#define MSR_R0_PMON_IPERF0_P3              0x00000e07U
#define MSR_R0_PMON_IPERF0_P4              0x00000e08U
#define MSR_R0_PMON_IPERF0_P5              0x00000e09U
#define MSR_R0_PMON_IPERF0_P6              0x00000e0aU
#define MSR_R0_PMON_IPERF0_P7              0x00000e0bU
#define MSR_R0_PMON_QLX_P0                 0x00000e0cU
#define MSR_R0_PMON_QLX_P1                 0x00000e0dU
#define MSR_R0_PMON_QLX_P2                 0x00000e0eU
#define MSR_R0_PMON_QLX_P3                 0x00000e0fU
#define MSR_R0_PMON_EVNT_SEL0              0x00000e10U
#define MSR_R0_PMON_CTR0                   0x00000e11U
#define MSR_R0_PMON_EVNT_SEL1              0x00000e12U
#define MSR_R0_PMON_CTR1                   0x00000e13U
#define MSR_R0_PMON_EVNT_SEL2              0x00000e14U
#define MSR_R0_PMON_CTR2                   0x00000e15U
#define MSR_R0_PMON_EVNT_SEL3              0x00000e16U
#define MSR_R0_PMON_CTR3                   0x00000e17U
#define MSR_R0_PMON_EVNT_SEL4              0x00000e18U
#define MSR_R0_PMON_CTR4                   0x00000e19U
#define MSR_R0_PMON_EVNT_SEL5              0x00000e1aU
#define MSR_R0_PMON_CTR5                   0x00000e1bU
#define MSR_R0_PMON_EVNT_SEL6              0x00000e1cU
#define MSR_R0_PMON_CTR6                   0x00000e1dU
#define MSR_R0_PMON_EVNT_SEL7              0x00000e1eU
#define MSR_R0_PMON_CTR7                   0x00000e1fU
#define MSR_R1_PMON_BOX_CTRL               0x00000e20U
#define MSR_R1_PMON_BOX_STATUS             0x00000e21U
#define MSR_R1_PMON_BOX_OVF_CTRL           0x00000e22U
#define MSR_R1_PMON_IPERF1_P8              0x00000e24U
#define MSR_R1_PMON_IPERF1_P9              0x00000e25U
#define MSR_R1_PMON_IPERF1_P10             0x00000e26U
#define MSR_R1_PMON_IPERF1_P11             0x00000e27U
#define MSR_R1_PMON_IPERF1_P12             0x00000e28U
#define MSR_R1_PMON_IPERF1_P13             0x00000e29U
#define MSR_R1_PMON_IPERF1_P14             0x00000e2aU
#define MSR_R1_PMON_IPERF1_P15             0x00000e2bU
#define MSR_R1_PMON_QLX_P4                 0x00000e2cU
#define MSR_R1_PMON_QLX_P5                 0x00000e2dU
#define MSR_R1_PMON_QLX_P6                 0x00000e2eU
#define MSR_R1_PMON_QLX_P7                 0x00000e2fU
#define MSR_R1_PMON_EVNT_SEL8              0x00000e30U
#define MSR_R1_PMON_CTR8                   0x00000e31U
#define MSR_R1_PMON_EVNT_SEL9              0x00000e32U
#define MSR_R1_PMON_CTR9                   0x00000e33U
#define MSR_R1_PMON_EVNT_SEL10             0x00000e34U
#define MSR_R1_PMON_CTR10                  0x00000e35U
#define MSR_R1_PMON_EVNT_SEL11             0x00000e36U
#define MSR_R1_PMON_CTR11                  0x00000e37U
#define MSR_R1_PMON_EVNT_SEL12             0x00000e38U
#define MSR_R1_PMON_CTR12                  0x00000e39U
#define MSR_R1_PMON_EVNT_SEL13             0x00000e3aU
#define MSR_R1_PMON_CTR13                  0x00000e3bU
#define MSR_R1_PMON_EVNT_SEL14             0x00000e3cU
#define MSR_R1_PMON_CTR14                  0x00000e3dU
#define MSR_R1_PMON_EVNT_SEL15             0x00000e3eU
#define MSR_R1_PMON_CTR15                  0x00000e3fU
#define MSR_B0_PMON_MATCH                  0x00000e45U
#define MSR_B0_PMON_MASK                   0x00000e46U
#define MSR_S0_PMON_MATCH                  0x00000e49U
#define MSR_S0_PMON_MASK                   0x00000e4aU
#define MSR_B1_PMON_MATCH                  0x00000e4dU
#define MSR_B1_PMON_MASK                   0x00000e4eU
#define MSR_M0_PMON_MM_CONFIG              0x00000e54U
#define MSR_M0_PMON_ADDR_MATCH             0x00000e55U
#define MSR_M0_PMON_ADDR_MASK              0x00000e56U
#define MSR_S1_PMON_MATCH                  0x00000e59U
#define MSR_S1_PMON_MASK                   0x00000e5aU
#define MSR_M1_PMON_MM_CONFIG              0x00000e5cU
#define MSR_M1_PMON_ADDR_MATCH             0x00000e5dU
#define MSR_M1_PMON_ADDR_MASK              0x00000e5eU



/*
 * 35.7 MSRS IN THE INTEL XEON PROCESSOR 5600 SERIES (BASED ON INTEL MICROARCHITECTURE CODE NAME WESTMERE)
 */
// All MSRs are already defined above



/*
 * 35.8 MSRS IN THE INTEL XEON PROCESSOR E7 FAMILY (BASED ON INTEL MICROARCHITECTURE CODE NAME WESTMERE)
 */
#define MSR_C8_PMON_BOX_CTRL        0x00000f40U
#define MSR_C8_PMON_BOX_STATUS      0x00000f41U
#define MSR_C8_PMON_BOX_OVF_CTRL    0x00000f42U
#define MSR_C8_PMON_EVNT_SEL0       0x00000f50U
#define MSR_C8_PMON_CTR0            0x00000f51U
#define MSR_C8_PMON_EVNT_SEL1       0x00000f52U
#define MSR_C8_PMON_CTR1            0x00000f53U
#define MSR_C8_PMON_EVNT_SEL2       0x00000f54U
#define MSR_C8_PMON_CTR2            0x00000f55U
#define MSR_C8_PMON_EVNT_SEL3       0x00000f56U
#define MSR_C8_PMON_CTR3            0x00000f57U



/*
 * 35.9 MSRS IN INTEL PROCESSOR FAMILY BASED ON INTEL MICROARCHITECTURE CODE NAME SANDY BRIDGE
 */
#define MSR_C8_PMON_EVNT_SEL4         0x00000f58U
#define MSR_C8_PMON_CTR4              0x00000f59U
#define MSR_C8_PMON_EVNT_SEL5         0x00000f5aU
#define MSR_C8_PMON_CTR5              0x00000f5bU
#define MSR_C9_PMON_BOX_CTRL          0x00000fc0U
#define MSR_C9_PMON_BOX_STATUS        0x00000fc1U
#define MSR_C9_PMON_BOX_OVF_CTRL      0x00000fc2U
#define MSR_C9_PMON_EVNT_SEL0         0x00000fd0U
#define MSR_C9_PMON_CTR0              0x00000fd1U
#define MSR_C9_PMON_EVNT_SEL1         0x00000fd2U
#define MSR_C9_PMON_CTR1              0x00000fd3U
#define MSR_C9_PMON_EVNT_SEL2         0x00000fd4U
#define MSR_C9_PMON_CTR2              0x00000fd5U
#define MSR_C9_PMON_EVNT_SEL3         0x00000fd6U
#define MSR_C9_PMON_CTR3              0x00000fd7U
#define MSR_C9_PMON_EVNT_SEL4         0x00000fd8U
#define MSR_C9_PMON_CTR4              0x00000fd9U
#define MSR_C9_PMON_EVNT_SEL5         0x00000fdaU
#define MSR_C9_PMON_CTR5              0x00000fdbU
#define MSR_IA32_PERFEVTSEL4          0x0000018aU
#define MSR_IA32_PERFEVTSEL5          0x0000018bU
#define MSR_IA32_PERFEVTSEL6          0x0000018cU
#define MSR_IA32_PERFEVTSEL7          0x0000018dU
#define MSR_CORE_C7_RESIDENCY         0x000003feU
#define MSR_PKGC6_IRTL                0x0000060bU
#define MSR_PKGC7_IRTL                0x0000060cU
#define MSR_PP0_POLICY                0x0000063aU
#define MSR_PP1_POWER_LIMIT           0x00000640U
#define MSR_PP1_POLICY                0x00000642U
#define MSR_UNC_PERF_GLOBAL_CTRL      0x00000391U
#define MSR_UNC_PERF_GLOBAL_STATUS    0x00000392U
#define MSR_UNC_PERF_FIXED_CTRL       0x00000394U
#define MSR_UNC_PERF_FIXED_CTR        0x00000395U
#define MSR_UNC_CBO_CONFIG            0x00000396U
#define MSR_UNC_ARB_PERFCTR0          0x000003b0U
#define MSR_UNC_ARB_PERFCTR1          0x000003b1U
#define MSR_UNC_ARB_PERFEVTSEL0       0x000003b2U
#define MSR_UNC_ARB_PERFEVTSEL1       0x000003b3U
#define MSR_UNC_CBO_0_PERFEVTSEL0     0x00000700U
#define MSR_UNC_CBO_0_PERFEVTSEL1     0x00000701U
#define MSR_UNC_CBO_0_PERFEVTSEL2     0x00000702U
#define MSR_UNC_CBO_0_PERFEVTSEL3     0x00000703U
#define MSR_UNC_CBO_0_UNIT_STATUS     0x00000705U
#define MSR_UNC_CBO_0_PERFCTR0        0x00000706U
#define MSR_UNC_CBO_0_PERFCTR1        0x00000707U
#define MSR_UNC_CBO_0_PERFCTR2        0x00000708U
#define MSR_UNC_CBO_0_PERFCTR3        0x00000709U
#define MSR_UNC_CBO_1_PERFEVTSEL0     0x00000710U
#define MSR_UNC_CBO_1_PERFEVTSEL1     0x00000711U
#define MSR_UNC_CBO_1_PERFEVTSEL2     0x00000712U
#define MSR_UNC_CBO_1_PERFEVTSEL3     0x00000713U
#define MSR_UNC_CBO_1_UNIT_STATUS     0x00000715U
#define MSR_UNC_CBO_1_PERFCTR0        0x00000716U
#define MSR_UNC_CBO_1_PERFCTR1        0x00000717U
#define MSR_UNC_CBO_1_PERFCTR2        0x00000718U
#define MSR_UNC_CBO_1_PERFCTR3        0x00000719U
#define MSR_UNC_CBO_2_PERFEVTSEL0     0x00000720U
#define MSR_UNC_CBO_2_PERFEVTSEL1     0x00000721U
#define MSR_UNC_CBO_2_PERFEVTSEL2     0x00000722U
#define MSR_UNC_CBO_2_PERFEVTSEL3     0x00000723U
#define MSR_UNC_CBO_2_UNIT_STATUS     0x00000725U
#define MSR_UNC_CBO_2_PERFCTR0        0x00000726U
#define MSR_UNC_CBO_2_PERFCTR1        0x00000727U
#define MSR_UNC_CBO_3_PERFCTR2        0x00000728U
#define MSR_UNC_CBO_3_PERFCTR3        0x00000729U
#define MSR_UNC_CBO_3_PERFEVTSEL0     0x00000730U
#define MSR_UNC_CBO_3_PERFEVTSEL1     0x00000731U
#define MSR_UNC_CBO_3_PERFEVTSEL2     0x00000732U
#define MSR_UNC_CBO_3_PERFEVTSEL3     0x00000733U
#define MSR_UNC_CBO_3_UNIT_STATUS     0x00000735U
#define MSR_UNC_CBO_3_PERFCTR0        0x00000736U
#define MSR_UNC_CBO_3_PERFCTR1        0x00000737U
#define MSR_UNC_CBO_4_PERFEVTSEL0     0x00000740U
#define MSR_UNC_CBO_4_PERFEVTSEL1     0x00000741U
#define MSR_UNC_CBO_4_PERFEVTSEL2     0x00000742U
#define MSR_UNC_CBO_4_PERFEVTSEL3     0x00000743U
#define MSR_UNC_CBO_4_UNIT_STATUS     0x00000745U
#define MSR_UNC_CBO_4_PERFCTR0        0x00000746U
#define MSR_UNC_CBO_4_PERFCTR1        0x00000747U
#define MSR_UNC_CBO_4_PERFCTR2        0x00000748U
#define MSR_UNC_CBO_4_PERFCTR3        0x00000749U
#define MSR_ERROR_CONTROL             0x0000017fU
#define MSR_PEBS_NUM_ALT              0x0000039cU
#define MSR_U_PMON_UCLK_FIXED_CTL     0x00000c08U
#define MSR_U_PMON_UCLK_FIXED_CTR     0x00000c09U
#define MSR_U_PMON_EVNTSEL0           0x00000c10U
#define MSR_U_PMON_EVNTSEL1           0x00000c11U
#define MSR_U_PMON_CTR0               0x00000c16U
#define MSR_U_PMON_CTR1               0x00000c17U
#define MSR_PCU_PMON_BOX_CTL          0x00000c24U
#define MSR_PCU_PMON_EVNTSEL0         0x00000c30U
#define MSR_PCU_PMON_EVNTSEL1         0x00000c31U
#define MSR_PCU_PMON_EVNTSEL2         0x00000c32U
#define MSR_PCU_PMON_EVNTSEL3         0x00000c33U
#define MSR_PCU_PMON_BOX_FILTER       0x00000c34U
#define MSR_PCU_PMON_CTR0             0x00000c36U
#define MSR_PCU_PMON_CTR1             0x00000c37U
#define MSR_PCU_PMON_CTR2             0x00000c38U
#define MSR_PCU_PMON_CTR3             0x00000c39U
#define MSR_C0_PMON_BOX_CTL           0x00000d04U
#define MSR_C0_PMON_EVNTSEL0          0x00000d10U
#define MSR_C0_PMON_EVNTSEL1          0x00000d11U
#define MSR_C0_PMON_EVNTSEL2          0x00000d12U
#define MSR_C0_PMON_EVNTSEL3          0x00000d13U
#define MSR_C0_PMON_BOX_FILTER        0x00000d14U
#define MSR_C1_PMON_BOX_CTL           0x00000d24U
#define MSR_C1_PMON_EVNTSEL0          0x00000d30U
#define MSR_C1_PMON_EVNTSEL1          0x00000d31U
#define MSR_C1_PMON_EVNTSEL2          0x00000d32U
#define MSR_C1_PMON_EVNTSEL3          0x00000d33U
#define MSR_C1_PMON_BOX_FILTER        0x00000d34U
#define MSR_C2_PMON_BOX_CTL           0x00000d44U
#define MSR_C2_PMON_EVNTSEL0          0x00000d50U
#define MSR_C2_PMON_EVNTSEL1          0x00000d51U
#define MSR_C2_PMON_EVNTSEL2          0x00000d52U
#define MSR_C2_PMON_EVNTSEL3          0x00000d53U
#define MSR_C2_PMON_BOX_FILTER        0x00000d54U
#define MSR_C3_PMON_BOX_CTL           0x00000d64U
#define MSR_C3_PMON_EVNTSEL0          0x00000d70U
#define MSR_C3_PMON_EVNTSEL1          0x00000d71U
#define MSR_C3_PMON_EVNTSEL2          0x00000d72U
#define MSR_C3_PMON_EVNTSEL3          0x00000d73U
#define MSR_C3_PMON_BOX_FILTER        0x00000d74U
#define MSR_C4_PMON_BOX_CTL           0x00000d84U
#define MSR_C4_PMON_EVNTSEL0          0x00000d90U
#define MSR_C4_PMON_EVNTSEL1          0x00000d91U
#define MSR_C4_PMON_EVNTSEL2          0x00000d92U
#define MSR_C4_PMON_EVNTSEL3          0x00000d93U
#define MSR_C4_PMON_BOX_FILTER        0x00000d94U
#define MSR_C5_PMON_BOX_CTL           0x00000da4U
#define MSR_C5_PMON_EVNTSEL0          0x00000db0U
#define MSR_C5_PMON_EVNTSEL1          0x00000db1U
#define MSR_C5_PMON_EVNTSEL2          0x00000db2U
#define MSR_C5_PMON_EVNTSEL3          0x00000db3U
#define MSR_C5_PMON_BOX_FILTER        0x00000db4U



/*
 * 35.10 MSRS IN THE 3RD GENERATION INTEL CORE PROCESSOR FAMILY (BASED ON INTEL MICROARCHITECTURE CODE NAME IVY BRIDGE)
 */
#define MSR_C6_PMON_BOX_CTL         0x00000dc4U
#define MSR_C6_PMON_EVNTSEL0        0x00000dd0U
#define MSR_C6_PMON_EVNTSEL1        0x00000dd1U
#define MSR_C6_PMON_EVNTSEL2        0x00000dd2U
#define MSR_C6_PMON_EVNTSEL3        0x00000dd3U
#define MSR_C6_PMON_BOX_FILTER      0x00000dd4U
#define MSR_C7_PMON_BOX_CTL         0x00000de4U
#define MSR_C7_PMON_EVNTSEL0        0x00000df0U
#define MSR_C7_PMON_EVNTSEL1        0x00000df1U
#define MSR_C7_PMON_EVNTSEL2        0x00000df2U
#define MSR_C7_PMON_EVNTSEL3        0x00000df3U
#define MSR_C7_PMON_BOX_FILTER      0x00000df4U
#define MSR_CONFIG_TDP_NOMINAL      0x00000648U
#define MSR_CONFIG_TDP_LEVEL1       0x00000649U
#define MSR_CONFIG_TDP_LEVEL2       0x0000064aU
#define MSR_CONFIG_TDP_CONTROL      0x0000064bU
#define MSR_PPIN_CTL                0x0000004eU
#define MSR_PPIN                    0x0000004fU
#define MSR_TURBO_RATIO_LIMIT1      0x000001aeU
#define MSR_IA32_MC2MISC            0x00000467U
#define MSR_IA32_MC29_CTL           0x00000474U
#define MSR_IA32_MC29_STATUS        0x00000475U
#define MSR_IA32_MC29_ADDR          0x00000476U
#define MSR_IA32_MC29_MISC          0x00000477U
#define MSR_IA32_MC30_CTL           0x00000478U
#define MSR_IA32_MC30_STATUS        0x00000479U
#define MSR_IA32_MC30_ADDR          0x0000047aU
#define MSR_IA32_MC30_MISC          0x0000047bU
#define MSR_IA32_MC31_CTL           0x0000047cU
#define MSR_IA32_MC31_STATUS        0x0000047dU
#define MSR_IA32_MC31_ADDR          0x0000047eU
#define MSR_IA32_MC31_MISC          0x0000047fU
#define MSR_PMON_GLOBAL_CTL         0x00000c00U
#define MSR_PMON_GLOBAL_STATUS      0x00000c01U
#define MSR_PMON_GLOBAL_CONFIG      0x00000c06U
#define MSR_U_PMON_BOX_STATUS       0x00000c15U
#define MSR_PCU_PMON_BOX_STATUS     0x00000c35U
#define MSR_C0_PMON_BOX_FILTER1     0x00000d1aU
#define MSR_C1_PMON_BOX_FILTER1     0x00000d3aU
#define MSR_C2_PMON_BOX_FILTER1     0x00000d5aU
#define MSR_C3_PMON_BOX_FILTER1     0x00000d7aU
#define MSR_C4_PMON_BOX_FILTER1     0x00000d9aU
#define MSR_C5_PMON_BOX_FILTER1     0x00000dbaU
#define MSR_C6_PMON_BOX_FILTER1     0x00000ddaU
#define MSR_C7_PMON_BOX_FILTER1     0x00000dfaU
#define MSR_C8_PMON_BOX_CTL         0x00000e04U
#define MSR_C8_PMON_EVNTSEL0        0x00000e10U
#define MSR_C8_PMON_EVNTSEL1        0x00000e11U
#define MSR_C8_PMON_EVNTSEL2        0x00000e12U
#define MSR_C8_PMON_EVNTSEL3        0x00000e13U
#define MSR_C8_PMON_BOX_FILTER      0x00000e14U
#define MSR_C8_PMON_BOX_FILTER1     0x00000e1aU
#define MSR_C9_PMON_BOX_CTL         0x00000e24U
#define MSR_C9_PMON_EVNTSEL0        0x00000e30U
#define MSR_C9_PMON_EVNTSEL1        0x00000e31U
#define MSR_C9_PMON_EVNTSEL2        0x00000e32U
#define MSR_C9_PMON_EVNTSEL3        0x00000e33U
#define MSR_C9_PMON_BOX_FILTER      0x00000e34U
#define MSR_C9_PMON_BOX_FILTER1     0x00000e3aU
#define MSR_C10_PMON_BOX_CTL        0x00000e44U
#define MSR_C10_PMON_EVNTSEL0       0x00000e50U
#define MSR_C10_PMON_EVNTSEL1       0x00000e51U
#define MSR_C10_PMON_EVNTSEL2       0x00000e52U
#define MSR_C10_PMON_EVNTSEL3       0x00000e53U
#define MSR_C10_PMON_BOX_FILTER     0x00000e54U
#define MSR_C10_PMON_CTR0           0x00000e56U
#define MSR_C10_PMON_CTR1           0x00000e57U
#define MSR_C10_PMON_CTR2           0x00000e58U
#define MSR_C10_PMON_CTR3           0x00000e59U
#define MSR_C10_PMON_BOX_FILTER1    0x00000e5aU
#define MSR_C11_PMON_BOX_CTL        0x00000e64U
#define MSR_C11_PMON_EVNTSEL0       0x00000e70U
#define MSR_C11_PMON_EVNTSEL1       0x00000e71U
#define MSR_C11_PMON_EVNTSEL2       0x00000e72U
#define MSR_C11_PMON_EVNTSEL3       0x00000e73U
#define MSR_C11_PMON_BOX_FILTER     0x00000e74U
#define MSR_C11_PMON_CTR0           0x00000e76U
#define MSR_C11_PMON_CTR1           0x00000e77U
#define MSR_C11_PMON_CTR2           0x00000e78U
#define MSR_C11_PMON_CTR3           0x00000e79U
#define MSR_C11_PMON_BOX_FILTER1    0x00000e7aU
#define MSR_C12_PMON_BOX_CTL        0x00000e84U
#define MSR_C12_PMON_EVNTSEL0       0x00000e90U
#define MSR_C12_PMON_EVNTSEL1       0x00000e91U
#define MSR_C12_PMON_EVNTSEL2       0x00000e92U
#define MSR_C12_PMON_EVNTSEL3       0x00000e93U
#define MSR_C12_PMON_BOX_FILTER     0x00000e94U
#define MSR_C12_PMON_CTR0           0x00000e96U
#define MSR_C12_PMON_CTR1           0x00000e97U
#define MSR_C12_PMON_CTR2           0x00000e98U
#define MSR_C12_PMON_CTR3           0x00000e99U
#define MSR_C12_PMON_BOX_FILTER1    0x00000e9aU
#define MSR_C13_PMON_BOX_CTL        0x00000ea4U



/*
 * 35.11 MSRS IN THE 4TH GENERATION INTEL CORE PROCESSORS (BASED ON HASWELL MICROARCHITECTURE)
 */
#define MSR_C13_PMON_EVNTSEL0              0x00000eb0U
#define MSR_C13_PMON_EVNTSEL1              0x00000eb1U
#define MSR_C13_PMON_EVNTSEL2              0x00000eb2U
#define MSR_C13_PMON_EVNTSEL3              0x00000eb3U
#define MSR_C13_PMON_BOX_FILTER            0x00000eb4U
#define MSR_C13_PMON_CTR0                  0x00000eb6U
#define MSR_C13_PMON_CTR1                  0x00000eb7U
#define MSR_C13_PMON_CTR2                  0x00000eb8U
#define MSR_C13_PMON_CTR3                  0x00000eb9U
#define MSR_C13_PMON_BOX_FILTER1           0x00000ebaU
#define MSR_C14_PMON_BOX_CTL               0x00000ec4U
#define MSR_C14_PMON_EVNTSEL0              0x00000ed0U
#define MSR_C14_PMON_EVNTSEL1              0x00000ed1U
#define MSR_C14_PMON_EVNTSEL2              0x00000ed2U
#define MSR_C14_PMON_EVNTSEL3              0x00000ed3U
#define MSR_C14_PMON_BOX_FILTER            0x00000ed4U
#define MSR_C14_PMON_CTR0                  0x00000ed6U
#define MSR_C14_PMON_CTR1                  0x00000ed7U
#define MSR_C14_PMON_CTR2                  0x00000ed8U
#define MSR_C14_PMON_CTR3                  0x00000ed9U
#define MSR_C14_PMON_BOX_FILTER1           0x00000edaU
#define MSR_GRAPHICS_PERF_LIMIT_REASONS    0x000006b0U
#define MSR_RING_PERF_LIMIT_REASONS        0x000006b1U
#define MSR_PKG_C8_RESIDENCY               0x00000630U
#define MSR_PKG_C9_RESIDENCY               0x00000631U



/*
 * 35.12 MSRS IN INTEL XEON PROCESSOR E5 V3 AND E7 V3 PRODUCT FAMILY
 */
#define MSR_CORE_THREAD_COUNT       0x00000035U
#define MSR_THREAD_ID_INFO          0x00000053U
#define MSR_TURBO_RATIO_LIMIT2      0x000001afU
#define MSR_PCIE_PLL_RATIO          0x0000061eU
#define MSR_S0_PMON_BOX_CTL         0x00000720U
#define MSR_S0_PMON_EVNTSEL0        0x00000721U
#define MSR_S0_PMON_EVNTSEL1        0x00000722U
#define MSR_S0_PMON_EVNTSEL2        0x00000723U
#define MSR_S0_PMON_EVNTSEL3        0x00000724U
#define MSR_S0_PMON_BOX_FILTER      0x00000725U
#define MSR_S1_PMON_BOX_CTL         0x0000072aU
#define MSR_S1_PMON_EVNTSEL0        0x0000072bU
#define MSR_S1_PMON_EVNTSEL1        0x0000072cU
#define MSR_S1_PMON_EVNTSEL2        0x0000072dU
#define MSR_S1_PMON_EVNTSEL3        0x0000072eU
#define MSR_S1_PMON_BOX_FILTER      0x0000072fU
#define MSR_S2_PMON_BOX_CTL         0x00000734U
#define MSR_S2_PMON_EVNTSEL0        0x00000735U
#define MSR_S2_PMON_EVNTSEL1        0x00000736U
#define MSR_S2_PMON_EVNTSEL2        0x00000737U
#define MSR_S2_PMON_EVNTSEL3        0x00000738U
#define MSR_S2_PMON_BOX_FILTER      0x00000739U
#define MSR_S2_PMON_CTR0            0x0000073aU
#define MSR_S2_PMON_CTR1            0x0000073bU
#define MSR_S2_PMON_CTR2            0x0000073cU
#define MSR_S2_PMON_CTR3            0x0000073dU
#define MSR_S3_PMON_BOX_CTL         0x0000073eU
#define MSR_S3_PMON_EVNTSEL0        0x0000073fU
#define MSR_S3_PMON_EVNTSEL1        0x00000740U
#define MSR_S3_PMON_EVNTSEL2        0x00000741U
#define MSR_S3_PMON_EVNTSEL3        0x00000742U
#define MSR_S3_PMON_BOX_FILTER      0x00000743U
#define MSR_S3_PMON_CTR0            0x00000744U
#define MSR_S3_PMON_CTR1            0x00000745U
#define MSR_S3_PMON_CTR2            0x00000746U
#define MSR_S3_PMON_CTR3            0x00000747U
#define MSR_C0_PMON_BOX_FILTER0     0x00000e05U
#define MSR_C1_PMON_BOX_FILTER0     0x00000e15U
#define MSR_C2_PMON_BOX_FILTER0     0x00000e25U
#define MSR_C3_PMON_BOX_FILTER0     0x00000e35U
#define MSR_C4_PMON_BOX_FILTER0     0x00000e45U
#define MSR_C5_PMON_BOX_FILTER0     0x00000e55U
#define MSR_C6_PMON_BOX_FILTER0     0x00000e65U
#define MSR_C7_PMON_BOX_FILTER0     0x00000e75U
#define MSR_C8_PMON_BOX_FILTER0     0x00000e85U
#define MSR_C9_PMON_BOX_FILTER0     0x00000e95U
#define MSR_C10_PMON_BOX_FILTER0    0x00000ea5U
#define MSR_C10_PMON_BOX_STATUS     0x00000ea7U
#define MSR_C11_PMON_BOX_FILTER0    0x00000eb5U
#define MSR_C11_PMON_BOX_STATUS     0x00000eb7U
#define MSR_C12_PMON_BOX_FILTER0    0x00000ec5U
#define MSR_C12_PMON_BOX_STATUS     0x00000ec7U
#define MSR_C13_PMON_BOX_FILTER0    0x00000ed5U
#define MSR_C13_PMON_BOX_STATUS     0x00000ed7U
#define MSR_C14_PMON_BOX_STATUS     0x00000ee7U
#define MSR_C15_PMON_BOX_CTL        0x00000ef0U
#define MSR_C15_PMON_EVNTSEL0       0x00000ef1U
#define MSR_C15_PMON_EVNTSEL1       0x00000ef2U
#define MSR_C15_PMON_EVNTSEL2       0x00000ef3U
#define MSR_C15_PMON_EVNTSEL3       0x00000ef4U
#define MSR_C15_PMON_BOX_FILTER0    0x00000ef5U
#define MSR_C15_PMON_BOX_FILTER1    0x00000ef6U
#define MSR_C15_PMON_BOX_STATUS     0x00000ef7U
#define MSR_C15_PMON_CTR0           0x00000ef8U
#define MSR_C15_PMON_CTR1           0x00000ef9U
#define MSR_C15_PMON_CTR2           0x00000efaU
#define MSR_C15_PMON_CTR3           0x00000efbU
#define MSR_C16_PMON_BOX_CTL        0x00000f00U
#define MSR_C16_PMON_EVNTSEL0       0x00000f01U
#define MSR_C16_PMON_EVNTSEL1       0x00000f02U
#define MSR_C16_PMON_EVNTSEL2       0x00000f03U
#define MSR_C16_PMON_EVNTSEL3       0x00000f04U
#define MSR_C16_PMON_BOX_FILTER0    0x00000f05U
#define MSR_C16_PMON_BOX_FILTER1    0x00000f06U
#define MSR_C16_PMON_BOX_STATUS     0x00000f07U
#define MSR_C16_PMON_CTR0           0x00000f08U
#define MSR_C16_PMON_CTR1           0x00000f09U
#define MSR_C16_PMON_CTR2           0x00000f0aU
#define MSR_C16_PMON_CTR3           0x00000e0bU
#define MSR_C17_PMON_BOX_CTL        0x00000f10U
#define MSR_C17_PMON_EVNTSEL0       0x00000f11U
#define MSR_C17_PMON_EVNTSEL1       0x00000f12U
#define MSR_C17_PMON_EVNTSEL2       0x00000f13U
#define MSR_C17_PMON_EVNTSEL3       0x00000f14U
#define MSR_C17_PMON_BOX_FILTER0    0x00000f15U
#define MSR_C17_PMON_BOX_FILTER1    0x00000f16U
#define MSR_C17_PMON_BOX_STATUS     0x00000f17U
#define MSR_C17_PMON_CTR0           0x00000f18U
#define MSR_C17_PMON_CTR1           0x00000f19U
#define MSR_C17_PMON_CTR2           0x00000f1aU



/*
 * 35.13 MSRS IN INTEL CORE M PROCESSORS AND 5TH GENERATION INTEL CORE PROCESSORS
 */
#define MSR_C17_PMON_CTR3    0x00000f1bU



/*
 * 35.14 MSRS IN INTEL XEON PROCESSORS E5 V4 FAMILY
 */
#define MSR_IA32_L3_QOS_MASK_0     0x00000c90U
#define MSR_IA32_L3_QOS_MASK_1     0x00000c91U
#define MSR_IA32_L3_QOS_MASK_2     0x00000c92U
#define MSR_IA32_L3_QOS_MASK_3     0x00000c93U
#define MSR_IA32_L3_QOS_MASK_4     0x00000c94U
#define MSR_IA32_L3_QOS_MASK_5     0x00000c95U
#define MSR_IA32_L3_QOS_MASK_6     0x00000c96U
#define MSR_IA32_L3_QOS_MASK_7     0x00000c97U
#define MSR_IA32_L3_QOS_MASK_8     0x00000c98U
#define MSR_IA32_L3_QOS_MASK_9     0x00000c99U
#define MSR_IA32_L3_QOS_MASK_10    0x00000c9aU
#define MSR_IA32_L3_QOS_MASK_11    0x00000c9bU
#define MSR_IA32_L3_QOS_MASK_12    0x00000c9cU
#define MSR_IA32_L3_QOS_MASK_13    0x00000c9dU
#define MSR_IA32_L3_QOS_MASK_14    0x00000c9eU
#define MSR_IA32_L3_QOS_MASK_15    0x00000c9fU
#define MSR_TURBO_RATIO_LIMIT3     0x000001acU



/*
 * 35.15 MSRS IN THE 6TH GENERATION INTEL CORE PROCESSORS
 */
#define MSR_PEBS_FRONTEND                0x000003f7U
#define MSR_PLATFORM_ENERGY_COUNTER      0x0000064dU
#define MSR_PPERF                        0x0000064eU
#define MSR_PKG_HDC_CONFIG               0x00000652U
#define MSR_CORE_HDC_RESIDENCY           0x00000653U
#define MSR_PKG_HDC_SHALLOW_RESIDENCY    0x00000655U
#define MSR_PKG_HDC_DEEP_RESIDENCY       0x00000656U
#define MSR_WEIGHTED_CORE_C0             0x00000658U
#define MSR_ANY_CORE_C0                  0x00000659U
#define MSR_ANY_GFXE_C0                  0x0000065aU
#define MSR_CORE_GFXE_OVERLAP_C0         0x0000065bU
#define MSR_PLATFORM_POWER_LIMIT         0x0000065cU
#define MSR_LBR_INFO_0                   0x00000dc0U
#define MSR_LBR_INFO_1                   0x00000dc1U
#define MSR_LBR_INFO_2                   0x00000dc2U
#define MSR_LBR_INFO_3                   0x00000dc3U
#define MSR_LBR_INFO_4                   0x00000dc4U
#define MSR_LBR_INFO_5                   0x00000dc5U
#define MSR_LBR_INFO_6                   0x00000dc6U
#define MSR_LBR_INFO_7                   0x00000dc7U
#define MSR_LBR_INFO_8                   0x00000dc8U
#define MSR_LBR_INFO_9                   0x00000dc9U
#define MSR_LBR_INFO_10                  0x00000dcaU
#define MSR_LBR_INFO_11                  0x00000dcbU
#define MSR_LBR_INFO_12                  0x00000dccU
#define MSR_LBR_INFO_13                  0x00000dcdU
#define MSR_LBR_INFO_14                  0x00000dceU
#define MSR_LBR_INFO_15                  0x00000dcfU
#define MSR_LBR_INFO_16                  0x00000dd0U
#define MSR_LBR_INFO_17                  0x00000dd1U
#define MSR_LBR_INFO_18                  0x00000dd2U
#define MSR_LBR_INFO_19                  0x00000dd3U
#define MSR_LBR_INFO_20                  0x00000dd4U
#define MSR_LBR_INFO_21                  0x00000dd5U
#define MSR_LBR_INFO_22                  0x00000dd6U
#define MSR_LBR_INFO_23                  0x00000dd7U
#define MSR_LBR_INFO_24                  0x00000dd8U
#define MSR_LBR_INFO_25                  0x00000dd9U
#define MSR_LBR_INFO_26                  0x00000ddaU
#define MSR_LBR_INFO_27                  0x00000ddbU
#define MSR_LBR_INFO_28                  0x00000ddcU
#define MSR_LBR_INFO_29                  0x00000dddU
#define MSR_LBR_INFO_30                  0x00000ddeU
#define MSR_LBR_INFO_31                  0x00000ddfU



/*
 * 35.16 MSRS IN FUTURE INTEL XEON PROCESSORS
 */
// All MSRs are already defined above



/*
 * 35.17 MSRS IN INTEL XEON PHI PROCESSOR 3200/5200/7200 SERIES
 */
#define MSR_MC0_RESIDENCY    0x000003fcU
#define MSR_MC6_RESIDENCY    0x000003fdU



/*
 * 35.18 MSRS IN THE PENTIUM 4 AND INTEL XEON PROCESSORS
 */
#define MSR_IA32_MONITOR_FILTER_LINE_SIZE    0x00000006U
#define MSR_EBC_HARD_POWERON                 0x0000002aU
#define MSR_EBC_SOFT_POWERON                 0x0000002bU
#define MSR_EBC_FREQUENCY_ID                 0x0000002cU
#define MSR_MCG_RAX                          0x00000180U
#define MSR_MCG_RBX                          0x00000181U
#define MSR_MCG_RCX                          0x00000182U
#define MSR_MCG_RDX                          0x00000183U
#define MSR_MCG_RSI                          0x00000184U
#define MSR_MCG_RDI                          0x00000185U
#define MSR_MCG_RBP                          0x00000186U
#define MSR_MCG_RSP                          0x00000187U
#define MSR_MCG_RFLAGS                       0x00000188U
#define MSR_MCG_RIP                          0x00000189U
#define MSR_MCG_MISC                         0x0000018aU
#define MSR_MCG_R8                           0x00000190U
#define MSR_MCG_R9                           0x00000191U
#define MSR_MCG_R10                          0x00000192U
#define MSR_MCG_R11                          0x00000193U
#define MSR_MCG_R12                          0x00000194U
#define MSR_MCG_R13                          0x00000195U
#define MSR_MCG_R14                          0x00000196U
#define MSR_MCG_R15                          0x00000197U
#define MSR_PLATFORM_BRV                     0x000001a1U
#define MSR_DEBUGCTLA                        0x000001d9U
#define MSR_LASTBRANCH_0                     0x000001dbU
#define MSR_LASTBRANCH_2                     0x000001ddU
#define MSR_LASTBRANCH_3                     0x000001deU
#define MSR_BPU_COUNTER0                     0x00000300U
#define MSR_BPU_COUNTER1                     0x00000301U
#define MSR_BPU_COUNTER2                     0x00000302U
#define MSR_BPU_COUNTER3                     0x00000303U
#define MSR_MS_COUNTER0                      0x00000304U
#define MSR_MS_COUNTER1                      0x00000305U
#define MSR_MS_COUNTER2                      0x00000306U
#define MSR_MS_COUNTER3                      0x00000307U
#define MSR_FLAME_COUNTER0                   0x00000308U
#define MSR_FLAME_COUNTER1                   0x00000309U
#define MSR_FLAME_COUNTER2                   0x0000030aU
#define MSR_FLAME_COUNTER3                   0x0000030bU
#define MSR_IQ_COUNTER0                      0x0000030cU
#define MSR_IQ_COUNTER1                      0x0000030dU
#define MSR_IQ_COUNTER2                      0x0000030eU
#define MSR_IQ_COUNTER3                      0x0000030fU
#define MSR_IQ_COUNTER4                      0x00000310U
#define MSR_IQ_COUNTER5                      0x00000311U
#define MSR_BPU_CCCR0                        0x00000360U
#define MSR_BPU_CCCR1                        0x00000361U
#define MSR_BPU_CCCR2                        0x00000362U
#define MSR_BPU_CCCR3                        0x00000363U
#define MSR_MS_CCCR0                         0x00000364U
#define MSR_MS_CCCR1                         0x00000365U
#define MSR_MS_CCCR2                         0x00000366U
#define MSR_MS_CCCR3                         0x00000367U
#define MSR_FLAME_CCCR0                      0x00000368U
#define MSR_FLAME_CCCR1                      0x00000369U
#define MSR_FLAME_CCCR2                      0x0000036aU
#define MSR_FLAME_CCCR3                      0x0000036bU
#define MSR_IQ_CCCR0                         0x0000036cU
#define MSR_IQ_CCCR1                         0x0000036dU
#define MSR_IQ_CCCR2                         0x0000036eU
#define MSR_IQ_CCCR3                         0x0000036fU
#define MSR_IQ_CCCR4                         0x00000370U
#define MSR_IQ_CCCR5                         0x00000371U
#define MSR_BSU_ESCR0                        0x000003a0U
#define MSR_BSU_ESCR1                        0x000003a1U
#define MSR_FSB_ESCR0                        0x000003a2U
#define MSR_FSB_ESCR1                        0x000003a3U
#define MSR_FIRM_ESCR0                       0x000003a4U
#define MSR_FIRM_ESCR1                       0x000003a5U
#define MSR_FLAME_ESCR0                      0x000003a6U
#define MSR_FLAME_ESCR1                      0x000003a7U
#define MSR_DAC_ESCR0                        0x000003a8U
#define MSR_DAC_ESCR1                        0x000003a9U
#define MSR_MOB_ESCR0                        0x000003aaU
#define MSR_MOB_ESCR1                        0x000003abU
#define MSR_PMH_ESCR0                        0x000003acU
#define MSR_PMH_ESCR1                        0x000003adU
#define MSR_SAAT_ESCR0                       0x000003aeU
#define MSR_SAAT_ESCR1                       0x000003afU
#define MSR_U2L_ESCR0                        0x000003b0U
#define MSR_U2L_ESCR1                        0x000003b1U
#define MSR_BPU_ESCR0                        0x000003b2U
#define MSR_BPU_ESCR1                        0x000003b3U
#define MSR_IS_ESCR0                         0x000003b4U
#define MSR_IS_ESCR1                         0x000003b5U
#define MSR_ITLB_ESCR0                       0x000003b6U
#define MSR_ITLB_ESCR1                       0x000003b7U
#define MSR_CRU_ESCR0                        0x000003b8U
#define MSR_CRU_ESCR1                        0x000003b9U
#define MSR_IQ_ESCR0                         0x000003baU
#define MSR_IQ_ESCR1                         0x000003bbU
#define MSR_RAT_ESCR0                        0x000003bcU
#define MSR_RAT_ESCR1                        0x000003bdU
#define MSR_SSU_ESCR0                        0x000003beU
#define MSR_MS_ESCR0                         0x000003c0U
#define MSR_MS_ESCR1                         0x000003c1U
#define MSR_TBPU_ESCR0                       0x000003c2U
#define MSR_TBPU_ESCR1                       0x000003c3U
#define MSR_TC_ESCR0                         0x000003c4U
#define MSR_TC_ESCR1                         0x000003c5U
#define MSR_IX_ESCR0                         0x000003c8U
#define MSR_IX_ESCR1                         0x000003c9U
#define MSR_ALF_ESCR0                        0x000003caU
#define MSR_ALF_ESCR1                        0x000003cbU
#define MSR_CRU_ESCR2                        0x000003ccU
#define MSR_CRU_ESCR3                        0x000003cdU
#define MSR_CRU_ESCR4                        0x000003e0U
#define MSR_CRU_ESCR5                        0x000003e1U
#define MSR_TC_PRECISE_EVENT                 0x000003f0U
#define MSR_PEBS_MATRIX_VERT                 0x000003f2U
#define MSR_IFSB_BUSQ0                       0x000107ccU
#define MSR_IFSB_BUSQ1                       0x000107cdU
#define MSR_IFSB_SNPQ0                       0x000107ceU
#define MSR_IFSB_SNPQ1                       0x000107cfU
#define MSR_EFSB_DRDY0                       0x000107d0U
#define MSR_EFSB_DRDY1                       0x000107d1U
#define MSR_IFSB_CTL6                        0x000107d2U
#define MSR_IFSB_CNTR7                       0x000107d3U



/*
 * 35.19 MSRS IN INTEL CORE SOLO AND INTEL CORE DUO PROCESSORS
 */
#define MSR_EMON_L3_CTR_CTL0     0x000107ccU
#define MSR_EMON_L3_CTR_CTL1     0x000107cdU
#define MSR_EMON_L3_CTR_CTL2     0x000107ceU
#define MSR_EMON_L3_CTR_CTL3     0x000107cfU
#define MSR_EMON_L3_CTR_CTL4     0x000107d0U
#define MSR_EMON_L3_CTR_CTL5     0x000107d1U
#define MSR_EMON_L3_CTR_CTL6     0x000107d2U
#define MSR_EMON_L3_CTR_CTL7     0x000107d3U
#define MSR_P5_MC_ADDR           0x00000000U
#define MSR_P5_MC_TYPE           0x00000001U
#define MSR_LASTBRANCH_1         0x00000041U
#define MSR_LASTBRANCH_4         0x00000044U
#define MSR_LASTBRANCH_5         0x00000045U
#define MSR_LASTBRANCH_6         0x00000046U
#define MSR_LASTBRANCH_7         0x00000047U
#define MSR_ROB_CR_BKUPTMPDR6    0x000001e0U
#define MSR_MTRRphysBase0        0x00000200U
#define MSR_MTRRphysMask0        0x00000201U
#define MSR_MTRRphysBase1        0x00000202U
#define MSR_MTRRphysMask1        0x00000203U
#define MSR_MTRRphysBase2        0x00000204U
#define MSR_MTRRphysMask2        0x00000205U
#define MSR_MTRRphysBase3        0x00000206U
#define MSR_MTRRphysMask3        0x00000207U
#define MSR_MTRRphysBase4        0x00000208U
#define MSR_MTRRphysMask4        0x00000209U
#define MSR_MTRRphysBase5        0x0000020aU
#define MSR_MTRRphysMask5        0x0000020bU
#define MSR_MTRRphysBase6        0x0000020cU
#define MSR_MTRRphysMask6        0x0000020dU
#define MSR_MTRRphysBase7        0x0000020eU
#define MSR_MTRRphysMask7        0x0000020fU
#define MSR_MTRRfix64K_00000     0x00000250U
#define MSR_MTRRfix16K_80000     0x00000258U
#define MSR_MTRRfix16K_A0000     0x00000259U
#define MSR_MTRRfix4K_C0000      0x00000268U
#define MSR_MTRRfix4K_C8000      0x00000269U
#define MSR_MTRRfix4K_D0000      0x0000026aU
#define MSR_MTRRfix4K_D8000      0x0000026bU
#define MSR_MTRRfix4K_E0000      0x0000026cU
#define MSR_MTRRfix4K_E8000      0x0000026dU
#define MSR_MTRRfix4K_F0000      0x0000026eU
#define MSR_MTRRfix4K_F8000      0x0000026fU
#define MSR_MC4_CTL              0x0000040cU
#define MSR_MC4_STATUS           0x0000040dU
#define MSR_MC4_ADDR             0x0000040eU
#define MSR_MC3_ADDR             0x00000412U
#define MSR_MC3_MISC             0x00000413U
#define MSR_MC5_CTL              0x00000414U
#define MSR_MC5_STATUS           0x00000415U
#define MSR_MC5_ADDR             0x00000416U
#define MSR_MC5_MISC             0x00000417U



/*
 * 35.20 MSRS IN THE PENTIUM M PROCESSOR
 */
#define MSR_BBL_CR_CTL30        0x0000011eU
#define MSR_IA32_MCG_STATUS0    0x0000017aU
#define MSR_DEBUGCTLB           0x000001d9U
#define MSR_MC3_CTL             0x00000410U
#define MSR_MC3_STATUS          0x00000411U



/*
 * 35.21 MSRS IN THE P6 FAMILY PROCESSORS
 */
#define MSR_TSC                 0x00000010U
#define MSR_APIC_BASE           0x0000001bU
#define MSR_TEST_CTL            0x00000033U
#define MSR_BIOS_UPDT_TRIG      0x00000079U
#define MSR_PerfCtr0            0x000000c1U
#define MSR_PerfCtr1            0x000000c2U
#define MSR_MTRRcap             0x000000feU
#define MSR_BBL_CR_ADDR         0x00000116U
#define MSR_BBL_CR_TRIG         0x0000011aU
#define MSR_BBL_CR_BUSY         0x0000011bU
#define MSR_SYSENTER_CS_MSR     0x00000174U
#define MSR_SYSENTER_ESP_MSR    0x00000175U
#define MSR_SYSENTER_EIP_MSR    0x00000176U
#define MSR_MCG_CAP             0x00000179U
#define MSR_MCG_STATUS          0x0000017aU
#define MSR_MCG_CTL             0x0000017bU
#define MSR_PerfEvtSel0         0x00000186U
#define MSR_PerfEvtSel1         0x00000187U
#define MSR_DEBUGCTLMSR0        0x000001d9U
#define MSR_LASTBRANCHFROMIP    0x000001dbU
#define MSR_LASTBRANCHTOIP      0x000001dcU
#define MSR_LASTINTFROMIP       0x000001ddU
#define MSR_LASTINTTOIP         0x000001deU
#define MSR_MC0_CTL             0x00000400U



/*
 * 35.22 MSRS IN PENTIUM PROCESSORS
 */
#define MSR_MC0_ADDR      0x00000402U
#define MSR_MC0_MISC      0x00000403U
#define MSR_MC1_CTL       0x00000404U
#define MSR_MC1_STATUS    0x00000405U
#define MSR_MC1_ADDR      0x00000406U
#define MSR_MC1_MISC      0x00000407U
#define MSR_MC2_CTL       0x00000408U
#define MSR_MC2_STATUS    0x00000409U
#define MSR_MC2_ADDR      0x0000040aU
#define MSR_MC2_MISC      0x0000040bU
#define MSR_MC4_MISC      0x0000040fU
#define MSR_CESR          0x00000011U
#define MSR_CTR0          0x00000012U
#define MSR_CTR1          0x00000013U
#endif
